
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `DiscussionModerator` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DiscussionModerator
 * 
 */
export type DiscussionModeratorModel = runtime.Types.Result.DefaultSelection<Prisma.$DiscussionModeratorPayload>

export type AggregateDiscussionModerator = {
  _count: DiscussionModeratorCountAggregateOutputType | null
  _min: DiscussionModeratorMinAggregateOutputType | null
  _max: DiscussionModeratorMaxAggregateOutputType | null
}

export type DiscussionModeratorMinAggregateOutputType = {
  id: string | null
  challengeId: string | null
  userId: string | null
  role: $Enums.ModeratorRole | null
  grantedAt: Date | null
  grantedById: string | null
}

export type DiscussionModeratorMaxAggregateOutputType = {
  id: string | null
  challengeId: string | null
  userId: string | null
  role: $Enums.ModeratorRole | null
  grantedAt: Date | null
  grantedById: string | null
}

export type DiscussionModeratorCountAggregateOutputType = {
  id: number
  challengeId: number
  userId: number
  role: number
  grantedAt: number
  grantedById: number
  _all: number
}


export type DiscussionModeratorMinAggregateInputType = {
  id?: true
  challengeId?: true
  userId?: true
  role?: true
  grantedAt?: true
  grantedById?: true
}

export type DiscussionModeratorMaxAggregateInputType = {
  id?: true
  challengeId?: true
  userId?: true
  role?: true
  grantedAt?: true
  grantedById?: true
}

export type DiscussionModeratorCountAggregateInputType = {
  id?: true
  challengeId?: true
  userId?: true
  role?: true
  grantedAt?: true
  grantedById?: true
  _all?: true
}

export type DiscussionModeratorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscussionModerator to aggregate.
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionModerators to fetch.
   */
  orderBy?: Prisma.DiscussionModeratorOrderByWithRelationInput | Prisma.DiscussionModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DiscussionModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DiscussionModerators
  **/
  _count?: true | DiscussionModeratorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DiscussionModeratorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DiscussionModeratorMaxAggregateInputType
}

export type GetDiscussionModeratorAggregateType<T extends DiscussionModeratorAggregateArgs> = {
      [P in keyof T & keyof AggregateDiscussionModerator]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDiscussionModerator[P]>
    : Prisma.GetScalarType<T[P], AggregateDiscussionModerator[P]>
}




export type DiscussionModeratorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DiscussionModeratorWhereInput
  orderBy?: Prisma.DiscussionModeratorOrderByWithAggregationInput | Prisma.DiscussionModeratorOrderByWithAggregationInput[]
  by: Prisma.DiscussionModeratorScalarFieldEnum[] | Prisma.DiscussionModeratorScalarFieldEnum
  having?: Prisma.DiscussionModeratorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DiscussionModeratorCountAggregateInputType | true
  _min?: DiscussionModeratorMinAggregateInputType
  _max?: DiscussionModeratorMaxAggregateInputType
}

export type DiscussionModeratorGroupByOutputType = {
  id: string
  challengeId: string
  userId: string
  role: $Enums.ModeratorRole
  grantedAt: Date
  grantedById: string
  _count: DiscussionModeratorCountAggregateOutputType | null
  _min: DiscussionModeratorMinAggregateOutputType | null
  _max: DiscussionModeratorMaxAggregateOutputType | null
}

type GetDiscussionModeratorGroupByPayload<T extends DiscussionModeratorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DiscussionModeratorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DiscussionModeratorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DiscussionModeratorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DiscussionModeratorGroupByOutputType[P]>
      }
    >
  > 



export type DiscussionModeratorWhereInput = {
  AND?: Prisma.DiscussionModeratorWhereInput | Prisma.DiscussionModeratorWhereInput[]
  OR?: Prisma.DiscussionModeratorWhereInput[]
  NOT?: Prisma.DiscussionModeratorWhereInput | Prisma.DiscussionModeratorWhereInput[]
  id?: Prisma.UuidFilter<"DiscussionModerator"> | string
  challengeId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  userId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  role?: Prisma.EnumModeratorRoleFilter<"DiscussionModerator"> | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFilter<"DiscussionModerator"> | Date | string
  grantedById?: Prisma.UuidFilter<"DiscussionModerator"> | string
  challenge?: Prisma.XOR<Prisma.ChallengeScalarRelationFilter, Prisma.ChallengeWhereInput>
  user?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  grantedBy?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}

export type DiscussionModeratorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  grantedById?: Prisma.SortOrder
  challenge?: Prisma.ChallengeOrderByWithRelationInput
  user?: Prisma.ProfileOrderByWithRelationInput
  grantedBy?: Prisma.ProfileOrderByWithRelationInput
}

export type DiscussionModeratorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  challengeId_userId?: Prisma.DiscussionModeratorChallengeIdUserIdCompoundUniqueInput
  AND?: Prisma.DiscussionModeratorWhereInput | Prisma.DiscussionModeratorWhereInput[]
  OR?: Prisma.DiscussionModeratorWhereInput[]
  NOT?: Prisma.DiscussionModeratorWhereInput | Prisma.DiscussionModeratorWhereInput[]
  challengeId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  userId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  role?: Prisma.EnumModeratorRoleFilter<"DiscussionModerator"> | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFilter<"DiscussionModerator"> | Date | string
  grantedById?: Prisma.UuidFilter<"DiscussionModerator"> | string
  challenge?: Prisma.XOR<Prisma.ChallengeScalarRelationFilter, Prisma.ChallengeWhereInput>
  user?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  grantedBy?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}, "id" | "challengeId_userId">

export type DiscussionModeratorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  grantedById?: Prisma.SortOrder
  _count?: Prisma.DiscussionModeratorCountOrderByAggregateInput
  _max?: Prisma.DiscussionModeratorMaxOrderByAggregateInput
  _min?: Prisma.DiscussionModeratorMinOrderByAggregateInput
}

export type DiscussionModeratorScalarWhereWithAggregatesInput = {
  AND?: Prisma.DiscussionModeratorScalarWhereWithAggregatesInput | Prisma.DiscussionModeratorScalarWhereWithAggregatesInput[]
  OR?: Prisma.DiscussionModeratorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DiscussionModeratorScalarWhereWithAggregatesInput | Prisma.DiscussionModeratorScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"DiscussionModerator"> | string
  challengeId?: Prisma.UuidWithAggregatesFilter<"DiscussionModerator"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"DiscussionModerator"> | string
  role?: Prisma.EnumModeratorRoleWithAggregatesFilter<"DiscussionModerator"> | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeWithAggregatesFilter<"DiscussionModerator"> | Date | string
  grantedById?: Prisma.UuidWithAggregatesFilter<"DiscussionModerator"> | string
}

export type DiscussionModeratorCreateInput = {
  id?: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  challenge: Prisma.ChallengeCreateNestedOneWithoutDiscussionModeratorsInput
  user: Prisma.ProfileCreateNestedOneWithoutModeratorRolesInput
  grantedBy: Prisma.ProfileCreateNestedOneWithoutGrantedModeratorsInput
}

export type DiscussionModeratorUncheckedCreateInput = {
  id?: string
  challengeId: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  challenge?: Prisma.ChallengeUpdateOneRequiredWithoutDiscussionModeratorsNestedInput
  user?: Prisma.ProfileUpdateOneRequiredWithoutModeratorRolesNestedInput
  grantedBy?: Prisma.ProfileUpdateOneRequiredWithoutGrantedModeratorsNestedInput
}

export type DiscussionModeratorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DiscussionModeratorCreateManyInput = {
  id?: string
  challengeId: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscussionModeratorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DiscussionModeratorListRelationFilter = {
  every?: Prisma.DiscussionModeratorWhereInput
  some?: Prisma.DiscussionModeratorWhereInput
  none?: Prisma.DiscussionModeratorWhereInput
}

export type DiscussionModeratorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DiscussionModeratorChallengeIdUserIdCompoundUniqueInput = {
  challengeId: string
  userId: string
}

export type DiscussionModeratorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  grantedById?: Prisma.SortOrder
}

export type DiscussionModeratorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  grantedById?: Prisma.SortOrder
}

export type DiscussionModeratorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  challengeId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  grantedById?: Prisma.SortOrder
}

export type DiscussionModeratorCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput> | Prisma.DiscussionModeratorCreateWithoutUserInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput | Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyUserInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorCreateNestedManyWithoutGrantedByInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput> | Prisma.DiscussionModeratorCreateWithoutGrantedByInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput | Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyGrantedByInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput> | Prisma.DiscussionModeratorCreateWithoutUserInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput | Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyUserInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorUncheckedCreateNestedManyWithoutGrantedByInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput> | Prisma.DiscussionModeratorCreateWithoutGrantedByInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput | Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyGrantedByInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput> | Prisma.DiscussionModeratorCreateWithoutUserInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput | Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutUserInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyUserInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutUserInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutUserInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type DiscussionModeratorUpdateManyWithoutGrantedByNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput> | Prisma.DiscussionModeratorCreateWithoutGrantedByInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput | Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutGrantedByInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutGrantedByInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyGrantedByInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutGrantedByInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutGrantedByInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutGrantedByInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutGrantedByInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type DiscussionModeratorUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput> | Prisma.DiscussionModeratorCreateWithoutUserInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput | Prisma.DiscussionModeratorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutUserInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyUserInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutUserInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutUserInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type DiscussionModeratorUncheckedUpdateManyWithoutGrantedByNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput> | Prisma.DiscussionModeratorCreateWithoutGrantedByInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput | Prisma.DiscussionModeratorCreateOrConnectWithoutGrantedByInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutGrantedByInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutGrantedByInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyGrantedByInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutGrantedByInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutGrantedByInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutGrantedByInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutGrantedByInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type DiscussionModeratorCreateNestedManyWithoutChallengeInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput> | Prisma.DiscussionModeratorCreateWithoutChallengeInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput | Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyChallengeInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorUncheckedCreateNestedManyWithoutChallengeInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput> | Prisma.DiscussionModeratorCreateWithoutChallengeInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput | Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyChallengeInputEnvelope
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
}

export type DiscussionModeratorUpdateManyWithoutChallengeNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput> | Prisma.DiscussionModeratorCreateWithoutChallengeInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput | Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutChallengeInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutChallengeInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyChallengeInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutChallengeInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutChallengeInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutChallengeInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutChallengeInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type DiscussionModeratorUncheckedUpdateManyWithoutChallengeNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput> | Prisma.DiscussionModeratorCreateWithoutChallengeInput[] | Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput[]
  connectOrCreate?: Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput | Prisma.DiscussionModeratorCreateOrConnectWithoutChallengeInput[]
  upsert?: Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutChallengeInput | Prisma.DiscussionModeratorUpsertWithWhereUniqueWithoutChallengeInput[]
  createMany?: Prisma.DiscussionModeratorCreateManyChallengeInputEnvelope
  set?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  disconnect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  delete?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  connect?: Prisma.DiscussionModeratorWhereUniqueInput | Prisma.DiscussionModeratorWhereUniqueInput[]
  update?: Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutChallengeInput | Prisma.DiscussionModeratorUpdateWithWhereUniqueWithoutChallengeInput[]
  updateMany?: Prisma.DiscussionModeratorUpdateManyWithWhereWithoutChallengeInput | Prisma.DiscussionModeratorUpdateManyWithWhereWithoutChallengeInput[]
  deleteMany?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
}

export type EnumModeratorRoleFieldUpdateOperationsInput = {
  set?: $Enums.ModeratorRole
}

export type DiscussionModeratorCreateWithoutUserInput = {
  id?: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  challenge: Prisma.ChallengeCreateNestedOneWithoutDiscussionModeratorsInput
  grantedBy: Prisma.ProfileCreateNestedOneWithoutGrantedModeratorsInput
}

export type DiscussionModeratorUncheckedCreateWithoutUserInput = {
  id?: string
  challengeId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorCreateOrConnectWithoutUserInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput>
}

export type DiscussionModeratorCreateManyUserInputEnvelope = {
  data: Prisma.DiscussionModeratorCreateManyUserInput | Prisma.DiscussionModeratorCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DiscussionModeratorCreateWithoutGrantedByInput = {
  id?: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  challenge: Prisma.ChallengeCreateNestedOneWithoutDiscussionModeratorsInput
  user: Prisma.ProfileCreateNestedOneWithoutModeratorRolesInput
}

export type DiscussionModeratorUncheckedCreateWithoutGrantedByInput = {
  id?: string
  challengeId: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
}

export type DiscussionModeratorCreateOrConnectWithoutGrantedByInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput>
}

export type DiscussionModeratorCreateManyGrantedByInputEnvelope = {
  data: Prisma.DiscussionModeratorCreateManyGrantedByInput | Prisma.DiscussionModeratorCreateManyGrantedByInput[]
  skipDuplicates?: boolean
}

export type DiscussionModeratorUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutUserInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutUserInput, Prisma.DiscussionModeratorUncheckedCreateWithoutUserInput>
}

export type DiscussionModeratorUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutUserInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutUserInput>
}

export type DiscussionModeratorUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DiscussionModeratorScalarWhereInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateManyMutationInput, Prisma.DiscussionModeratorUncheckedUpdateManyWithoutUserInput>
}

export type DiscussionModeratorScalarWhereInput = {
  AND?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
  OR?: Prisma.DiscussionModeratorScalarWhereInput[]
  NOT?: Prisma.DiscussionModeratorScalarWhereInput | Prisma.DiscussionModeratorScalarWhereInput[]
  id?: Prisma.UuidFilter<"DiscussionModerator"> | string
  challengeId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  userId?: Prisma.UuidFilter<"DiscussionModerator"> | string
  role?: Prisma.EnumModeratorRoleFilter<"DiscussionModerator"> | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFilter<"DiscussionModerator"> | Date | string
  grantedById?: Prisma.UuidFilter<"DiscussionModerator"> | string
}

export type DiscussionModeratorUpsertWithWhereUniqueWithoutGrantedByInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutGrantedByInput>
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedCreateWithoutGrantedByInput>
}

export type DiscussionModeratorUpdateWithWhereUniqueWithoutGrantedByInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutGrantedByInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutGrantedByInput>
}

export type DiscussionModeratorUpdateManyWithWhereWithoutGrantedByInput = {
  where: Prisma.DiscussionModeratorScalarWhereInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateManyMutationInput, Prisma.DiscussionModeratorUncheckedUpdateManyWithoutGrantedByInput>
}

export type DiscussionModeratorCreateWithoutChallengeInput = {
  id?: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  user: Prisma.ProfileCreateNestedOneWithoutModeratorRolesInput
  grantedBy: Prisma.ProfileCreateNestedOneWithoutGrantedModeratorsInput
}

export type DiscussionModeratorUncheckedCreateWithoutChallengeInput = {
  id?: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorCreateOrConnectWithoutChallengeInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput>
}

export type DiscussionModeratorCreateManyChallengeInputEnvelope = {
  data: Prisma.DiscussionModeratorCreateManyChallengeInput | Prisma.DiscussionModeratorCreateManyChallengeInput[]
  skipDuplicates?: boolean
}

export type DiscussionModeratorUpsertWithWhereUniqueWithoutChallengeInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutChallengeInput>
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedCreateWithoutChallengeInput>
}

export type DiscussionModeratorUpdateWithWhereUniqueWithoutChallengeInput = {
  where: Prisma.DiscussionModeratorWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateWithoutChallengeInput, Prisma.DiscussionModeratorUncheckedUpdateWithoutChallengeInput>
}

export type DiscussionModeratorUpdateManyWithWhereWithoutChallengeInput = {
  where: Prisma.DiscussionModeratorScalarWhereInput
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateManyMutationInput, Prisma.DiscussionModeratorUncheckedUpdateManyWithoutChallengeInput>
}

export type DiscussionModeratorCreateManyUserInput = {
  id?: string
  challengeId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorCreateManyGrantedByInput = {
  id?: string
  challengeId: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
}

export type DiscussionModeratorUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  challenge?: Prisma.ChallengeUpdateOneRequiredWithoutDiscussionModeratorsNestedInput
  grantedBy?: Prisma.ProfileUpdateOneRequiredWithoutGrantedModeratorsNestedInput
}

export type DiscussionModeratorUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DiscussionModeratorUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DiscussionModeratorUpdateWithoutGrantedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  challenge?: Prisma.ChallengeUpdateOneRequiredWithoutDiscussionModeratorsNestedInput
  user?: Prisma.ProfileUpdateOneRequiredWithoutModeratorRolesNestedInput
}

export type DiscussionModeratorUncheckedUpdateWithoutGrantedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscussionModeratorUncheckedUpdateManyWithoutGrantedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  challengeId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscussionModeratorCreateManyChallengeInput = {
  id?: string
  userId: string
  role?: $Enums.ModeratorRole
  grantedAt?: Date | string
  grantedById: string
}

export type DiscussionModeratorUpdateWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.ProfileUpdateOneRequiredWithoutModeratorRolesNestedInput
  grantedBy?: Prisma.ProfileUpdateOneRequiredWithoutGrantedModeratorsNestedInput
}

export type DiscussionModeratorUncheckedUpdateWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DiscussionModeratorUncheckedUpdateManyWithoutChallengeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumModeratorRoleFieldUpdateOperationsInput | $Enums.ModeratorRole
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grantedById?: Prisma.StringFieldUpdateOperationsInput | string
}



export type DiscussionModeratorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  userId?: boolean
  role?: boolean
  grantedAt?: boolean
  grantedById?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionModerator"]>

export type DiscussionModeratorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  userId?: boolean
  role?: boolean
  grantedAt?: boolean
  grantedById?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionModerator"]>

export type DiscussionModeratorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  challengeId?: boolean
  userId?: boolean
  role?: boolean
  grantedAt?: boolean
  grantedById?: boolean
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionModerator"]>

export type DiscussionModeratorSelectScalar = {
  id?: boolean
  challengeId?: boolean
  userId?: boolean
  role?: boolean
  grantedAt?: boolean
  grantedById?: boolean
}

export type DiscussionModeratorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "challengeId" | "userId" | "role" | "grantedAt" | "grantedById", ExtArgs["result"]["discussionModerator"]>
export type DiscussionModeratorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type DiscussionModeratorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type DiscussionModeratorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  challenge?: boolean | Prisma.ChallengeDefaultArgs<ExtArgs>
  user?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  grantedBy?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}

export type $DiscussionModeratorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DiscussionModerator"
  objects: {
    challenge: Prisma.$ChallengePayload<ExtArgs>
    user: Prisma.$ProfilePayload<ExtArgs>
    grantedBy: Prisma.$ProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    challengeId: string
    userId: string
    role: $Enums.ModeratorRole
    grantedAt: Date
    grantedById: string
  }, ExtArgs["result"]["discussionModerator"]>
  composites: {}
}

export type DiscussionModeratorGetPayload<S extends boolean | null | undefined | DiscussionModeratorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload, S>

export type DiscussionModeratorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DiscussionModeratorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DiscussionModeratorCountAggregateInputType | true
  }

export interface DiscussionModeratorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DiscussionModerator'], meta: { name: 'DiscussionModerator' } }
  /**
   * Find zero or one DiscussionModerator that matches the filter.
   * @param {DiscussionModeratorFindUniqueArgs} args - Arguments to find a DiscussionModerator
   * @example
   * // Get one DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DiscussionModeratorFindUniqueArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DiscussionModerator that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DiscussionModeratorFindUniqueOrThrowArgs} args - Arguments to find a DiscussionModerator
   * @example
   * // Get one DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DiscussionModeratorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscussionModerator that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorFindFirstArgs} args - Arguments to find a DiscussionModerator
   * @example
   * // Get one DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DiscussionModeratorFindFirstArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorFindFirstArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscussionModerator that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorFindFirstOrThrowArgs} args - Arguments to find a DiscussionModerator
   * @example
   * // Get one DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DiscussionModeratorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DiscussionModerators that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DiscussionModerators
   * const discussionModerators = await prisma.discussionModerator.findMany()
   * 
   * // Get first 10 DiscussionModerators
   * const discussionModerators = await prisma.discussionModerator.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const discussionModeratorWithIdOnly = await prisma.discussionModerator.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DiscussionModeratorFindManyArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DiscussionModerator.
   * @param {DiscussionModeratorCreateArgs} args - Arguments to create a DiscussionModerator.
   * @example
   * // Create one DiscussionModerator
   * const DiscussionModerator = await prisma.discussionModerator.create({
   *   data: {
   *     // ... data to create a DiscussionModerator
   *   }
   * })
   * 
   */
  create<T extends DiscussionModeratorCreateArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorCreateArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DiscussionModerators.
   * @param {DiscussionModeratorCreateManyArgs} args - Arguments to create many DiscussionModerators.
   * @example
   * // Create many DiscussionModerators
   * const discussionModerator = await prisma.discussionModerator.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DiscussionModeratorCreateManyArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DiscussionModerators and returns the data saved in the database.
   * @param {DiscussionModeratorCreateManyAndReturnArgs} args - Arguments to create many DiscussionModerators.
   * @example
   * // Create many DiscussionModerators
   * const discussionModerator = await prisma.discussionModerator.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DiscussionModerators and only return the `id`
   * const discussionModeratorWithIdOnly = await prisma.discussionModerator.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DiscussionModeratorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DiscussionModerator.
   * @param {DiscussionModeratorDeleteArgs} args - Arguments to delete one DiscussionModerator.
   * @example
   * // Delete one DiscussionModerator
   * const DiscussionModerator = await prisma.discussionModerator.delete({
   *   where: {
   *     // ... filter to delete one DiscussionModerator
   *   }
   * })
   * 
   */
  delete<T extends DiscussionModeratorDeleteArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorDeleteArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DiscussionModerator.
   * @param {DiscussionModeratorUpdateArgs} args - Arguments to update one DiscussionModerator.
   * @example
   * // Update one DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DiscussionModeratorUpdateArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorUpdateArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DiscussionModerators.
   * @param {DiscussionModeratorDeleteManyArgs} args - Arguments to filter DiscussionModerators to delete.
   * @example
   * // Delete a few DiscussionModerators
   * const { count } = await prisma.discussionModerator.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DiscussionModeratorDeleteManyArgs>(args?: Prisma.SelectSubset<T, DiscussionModeratorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscussionModerators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DiscussionModerators
   * const discussionModerator = await prisma.discussionModerator.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DiscussionModeratorUpdateManyArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscussionModerators and returns the data updated in the database.
   * @param {DiscussionModeratorUpdateManyAndReturnArgs} args - Arguments to update many DiscussionModerators.
   * @example
   * // Update many DiscussionModerators
   * const discussionModerator = await prisma.discussionModerator.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DiscussionModerators and only return the `id`
   * const discussionModeratorWithIdOnly = await prisma.discussionModerator.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DiscussionModeratorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DiscussionModerator.
   * @param {DiscussionModeratorUpsertArgs} args - Arguments to update or create a DiscussionModerator.
   * @example
   * // Update or create a DiscussionModerator
   * const discussionModerator = await prisma.discussionModerator.upsert({
   *   create: {
   *     // ... data to create a DiscussionModerator
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DiscussionModerator we want to update
   *   }
   * })
   */
  upsert<T extends DiscussionModeratorUpsertArgs>(args: Prisma.SelectSubset<T, DiscussionModeratorUpsertArgs<ExtArgs>>): Prisma.Prisma__DiscussionModeratorClient<runtime.Types.Result.GetResult<Prisma.$DiscussionModeratorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DiscussionModerators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorCountArgs} args - Arguments to filter DiscussionModerators to count.
   * @example
   * // Count the number of DiscussionModerators
   * const count = await prisma.discussionModerator.count({
   *   where: {
   *     // ... the filter for the DiscussionModerators we want to count
   *   }
   * })
  **/
  count<T extends DiscussionModeratorCountArgs>(
    args?: Prisma.Subset<T, DiscussionModeratorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DiscussionModeratorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DiscussionModerator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DiscussionModeratorAggregateArgs>(args: Prisma.Subset<T, DiscussionModeratorAggregateArgs>): Prisma.PrismaPromise<GetDiscussionModeratorAggregateType<T>>

  /**
   * Group by DiscussionModerator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionModeratorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DiscussionModeratorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DiscussionModeratorGroupByArgs['orderBy'] }
      : { orderBy?: DiscussionModeratorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DiscussionModeratorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDiscussionModeratorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DiscussionModerator model
 */
readonly fields: DiscussionModeratorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DiscussionModerator.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DiscussionModeratorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  challenge<T extends Prisma.ChallengeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChallengeDefaultArgs<ExtArgs>>): Prisma.Prisma__ChallengeClient<runtime.Types.Result.GetResult<Prisma.$ChallengePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  grantedBy<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DiscussionModerator model
 */
export interface DiscussionModeratorFieldRefs {
  readonly id: Prisma.FieldRef<"DiscussionModerator", 'String'>
  readonly challengeId: Prisma.FieldRef<"DiscussionModerator", 'String'>
  readonly userId: Prisma.FieldRef<"DiscussionModerator", 'String'>
  readonly role: Prisma.FieldRef<"DiscussionModerator", 'ModeratorRole'>
  readonly grantedAt: Prisma.FieldRef<"DiscussionModerator", 'DateTime'>
  readonly grantedById: Prisma.FieldRef<"DiscussionModerator", 'String'>
}
    

// Custom InputTypes
/**
 * DiscussionModerator findUnique
 */
export type DiscussionModeratorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionModerator to fetch.
   */
  where: Prisma.DiscussionModeratorWhereUniqueInput
}

/**
 * DiscussionModerator findUniqueOrThrow
 */
export type DiscussionModeratorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionModerator to fetch.
   */
  where: Prisma.DiscussionModeratorWhereUniqueInput
}

/**
 * DiscussionModerator findFirst
 */
export type DiscussionModeratorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionModerator to fetch.
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionModerators to fetch.
   */
  orderBy?: Prisma.DiscussionModeratorOrderByWithRelationInput | Prisma.DiscussionModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscussionModerators.
   */
  cursor?: Prisma.DiscussionModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscussionModerators.
   */
  distinct?: Prisma.DiscussionModeratorScalarFieldEnum | Prisma.DiscussionModeratorScalarFieldEnum[]
}

/**
 * DiscussionModerator findFirstOrThrow
 */
export type DiscussionModeratorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionModerator to fetch.
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionModerators to fetch.
   */
  orderBy?: Prisma.DiscussionModeratorOrderByWithRelationInput | Prisma.DiscussionModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscussionModerators.
   */
  cursor?: Prisma.DiscussionModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionModerators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscussionModerators.
   */
  distinct?: Prisma.DiscussionModeratorScalarFieldEnum | Prisma.DiscussionModeratorScalarFieldEnum[]
}

/**
 * DiscussionModerator findMany
 */
export type DiscussionModeratorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionModerators to fetch.
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionModerators to fetch.
   */
  orderBy?: Prisma.DiscussionModeratorOrderByWithRelationInput | Prisma.DiscussionModeratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DiscussionModerators.
   */
  cursor?: Prisma.DiscussionModeratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionModerators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionModerators.
   */
  skip?: number
  distinct?: Prisma.DiscussionModeratorScalarFieldEnum | Prisma.DiscussionModeratorScalarFieldEnum[]
}

/**
 * DiscussionModerator create
 */
export type DiscussionModeratorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * The data needed to create a DiscussionModerator.
   */
  data: Prisma.XOR<Prisma.DiscussionModeratorCreateInput, Prisma.DiscussionModeratorUncheckedCreateInput>
}

/**
 * DiscussionModerator createMany
 */
export type DiscussionModeratorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DiscussionModerators.
   */
  data: Prisma.DiscussionModeratorCreateManyInput | Prisma.DiscussionModeratorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DiscussionModerator createManyAndReturn
 */
export type DiscussionModeratorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * The data used to create many DiscussionModerators.
   */
  data: Prisma.DiscussionModeratorCreateManyInput | Prisma.DiscussionModeratorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DiscussionModerator update
 */
export type DiscussionModeratorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * The data needed to update a DiscussionModerator.
   */
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateInput, Prisma.DiscussionModeratorUncheckedUpdateInput>
  /**
   * Choose, which DiscussionModerator to update.
   */
  where: Prisma.DiscussionModeratorWhereUniqueInput
}

/**
 * DiscussionModerator updateMany
 */
export type DiscussionModeratorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DiscussionModerators.
   */
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateManyMutationInput, Prisma.DiscussionModeratorUncheckedUpdateManyInput>
  /**
   * Filter which DiscussionModerators to update
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * Limit how many DiscussionModerators to update.
   */
  limit?: number
}

/**
 * DiscussionModerator updateManyAndReturn
 */
export type DiscussionModeratorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * The data used to update DiscussionModerators.
   */
  data: Prisma.XOR<Prisma.DiscussionModeratorUpdateManyMutationInput, Prisma.DiscussionModeratorUncheckedUpdateManyInput>
  /**
   * Filter which DiscussionModerators to update
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * Limit how many DiscussionModerators to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DiscussionModerator upsert
 */
export type DiscussionModeratorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * The filter to search for the DiscussionModerator to update in case it exists.
   */
  where: Prisma.DiscussionModeratorWhereUniqueInput
  /**
   * In case the DiscussionModerator found by the `where` argument doesn't exist, create a new DiscussionModerator with this data.
   */
  create: Prisma.XOR<Prisma.DiscussionModeratorCreateInput, Prisma.DiscussionModeratorUncheckedCreateInput>
  /**
   * In case the DiscussionModerator was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DiscussionModeratorUpdateInput, Prisma.DiscussionModeratorUncheckedUpdateInput>
}

/**
 * DiscussionModerator delete
 */
export type DiscussionModeratorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
  /**
   * Filter which DiscussionModerator to delete.
   */
  where: Prisma.DiscussionModeratorWhereUniqueInput
}

/**
 * DiscussionModerator deleteMany
 */
export type DiscussionModeratorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscussionModerators to delete
   */
  where?: Prisma.DiscussionModeratorWhereInput
  /**
   * Limit how many DiscussionModerators to delete.
   */
  limit?: number
}

/**
 * DiscussionModerator without action
 */
export type DiscussionModeratorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionModerator
   */
  select?: Prisma.DiscussionModeratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionModerator
   */
  omit?: Prisma.DiscussionModeratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionModeratorInclude<ExtArgs> | null
}
