
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `MilestoneProgress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MilestoneProgress
 * 
 */
export type MilestoneProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$MilestoneProgressPayload>

export type AggregateMilestoneProgress = {
  _count: MilestoneProgressCountAggregateOutputType | null
  _avg: MilestoneProgressAvgAggregateOutputType | null
  _sum: MilestoneProgressSumAggregateOutputType | null
  _min: MilestoneProgressMinAggregateOutputType | null
  _max: MilestoneProgressMaxAggregateOutputType | null
}

export type MilestoneProgressAvgAggregateOutputType = {
  currentValue: number | null
}

export type MilestoneProgressSumAggregateOutputType = {
  currentValue: number | null
}

export type MilestoneProgressMinAggregateOutputType = {
  id: string | null
  milestoneId: string | null
  participantId: string | null
  currentValue: number | null
  isAchieved: boolean | null
  achievedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MilestoneProgressMaxAggregateOutputType = {
  id: string | null
  milestoneId: string | null
  participantId: string | null
  currentValue: number | null
  isAchieved: boolean | null
  achievedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MilestoneProgressCountAggregateOutputType = {
  id: number
  milestoneId: number
  participantId: number
  currentValue: number
  isAchieved: number
  achievedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MilestoneProgressAvgAggregateInputType = {
  currentValue?: true
}

export type MilestoneProgressSumAggregateInputType = {
  currentValue?: true
}

export type MilestoneProgressMinAggregateInputType = {
  id?: true
  milestoneId?: true
  participantId?: true
  currentValue?: true
  isAchieved?: true
  achievedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MilestoneProgressMaxAggregateInputType = {
  id?: true
  milestoneId?: true
  participantId?: true
  currentValue?: true
  isAchieved?: true
  achievedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MilestoneProgressCountAggregateInputType = {
  id?: true
  milestoneId?: true
  participantId?: true
  currentValue?: true
  isAchieved?: true
  achievedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MilestoneProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MilestoneProgress to aggregate.
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MilestoneProgresses to fetch.
   */
  orderBy?: Prisma.MilestoneProgressOrderByWithRelationInput | Prisma.MilestoneProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MilestoneProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MilestoneProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MilestoneProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MilestoneProgresses
  **/
  _count?: true | MilestoneProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MilestoneProgressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MilestoneProgressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MilestoneProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MilestoneProgressMaxAggregateInputType
}

export type GetMilestoneProgressAggregateType<T extends MilestoneProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateMilestoneProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMilestoneProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateMilestoneProgress[P]>
}




export type MilestoneProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MilestoneProgressWhereInput
  orderBy?: Prisma.MilestoneProgressOrderByWithAggregationInput | Prisma.MilestoneProgressOrderByWithAggregationInput[]
  by: Prisma.MilestoneProgressScalarFieldEnum[] | Prisma.MilestoneProgressScalarFieldEnum
  having?: Prisma.MilestoneProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MilestoneProgressCountAggregateInputType | true
  _avg?: MilestoneProgressAvgAggregateInputType
  _sum?: MilestoneProgressSumAggregateInputType
  _min?: MilestoneProgressMinAggregateInputType
  _max?: MilestoneProgressMaxAggregateInputType
}

export type MilestoneProgressGroupByOutputType = {
  id: string
  milestoneId: string
  participantId: string
  currentValue: number
  isAchieved: boolean
  achievedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: MilestoneProgressCountAggregateOutputType | null
  _avg: MilestoneProgressAvgAggregateOutputType | null
  _sum: MilestoneProgressSumAggregateOutputType | null
  _min: MilestoneProgressMinAggregateOutputType | null
  _max: MilestoneProgressMaxAggregateOutputType | null
}

type GetMilestoneProgressGroupByPayload<T extends MilestoneProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MilestoneProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MilestoneProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MilestoneProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MilestoneProgressGroupByOutputType[P]>
      }
    >
  > 



export type MilestoneProgressWhereInput = {
  AND?: Prisma.MilestoneProgressWhereInput | Prisma.MilestoneProgressWhereInput[]
  OR?: Prisma.MilestoneProgressWhereInput[]
  NOT?: Prisma.MilestoneProgressWhereInput | Prisma.MilestoneProgressWhereInput[]
  id?: Prisma.UuidFilter<"MilestoneProgress"> | string
  milestoneId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  participantId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  currentValue?: Prisma.IntFilter<"MilestoneProgress"> | number
  isAchieved?: Prisma.BoolFilter<"MilestoneProgress"> | boolean
  achievedAt?: Prisma.DateTimeNullableFilter<"MilestoneProgress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
  milestone?: Prisma.XOR<Prisma.MilestoneScalarRelationFilter, Prisma.MilestoneWhereInput>
  participant?: Prisma.XOR<Prisma.ChallengeParticipantScalarRelationFilter, Prisma.ChallengeParticipantWhereInput>
}

export type MilestoneProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  milestoneId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  isAchieved?: Prisma.SortOrder
  achievedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  milestone?: Prisma.MilestoneOrderByWithRelationInput
  participant?: Prisma.ChallengeParticipantOrderByWithRelationInput
}

export type MilestoneProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  milestoneId_participantId?: Prisma.MilestoneProgressMilestoneIdParticipantIdCompoundUniqueInput
  AND?: Prisma.MilestoneProgressWhereInput | Prisma.MilestoneProgressWhereInput[]
  OR?: Prisma.MilestoneProgressWhereInput[]
  NOT?: Prisma.MilestoneProgressWhereInput | Prisma.MilestoneProgressWhereInput[]
  milestoneId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  participantId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  currentValue?: Prisma.IntFilter<"MilestoneProgress"> | number
  isAchieved?: Prisma.BoolFilter<"MilestoneProgress"> | boolean
  achievedAt?: Prisma.DateTimeNullableFilter<"MilestoneProgress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
  milestone?: Prisma.XOR<Prisma.MilestoneScalarRelationFilter, Prisma.MilestoneWhereInput>
  participant?: Prisma.XOR<Prisma.ChallengeParticipantScalarRelationFilter, Prisma.ChallengeParticipantWhereInput>
}, "id" | "milestoneId_participantId">

export type MilestoneProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  milestoneId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  isAchieved?: Prisma.SortOrder
  achievedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MilestoneProgressCountOrderByAggregateInput
  _avg?: Prisma.MilestoneProgressAvgOrderByAggregateInput
  _max?: Prisma.MilestoneProgressMaxOrderByAggregateInput
  _min?: Prisma.MilestoneProgressMinOrderByAggregateInput
  _sum?: Prisma.MilestoneProgressSumOrderByAggregateInput
}

export type MilestoneProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.MilestoneProgressScalarWhereWithAggregatesInput | Prisma.MilestoneProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.MilestoneProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MilestoneProgressScalarWhereWithAggregatesInput | Prisma.MilestoneProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MilestoneProgress"> | string
  milestoneId?: Prisma.UuidWithAggregatesFilter<"MilestoneProgress"> | string
  participantId?: Prisma.UuidWithAggregatesFilter<"MilestoneProgress"> | string
  currentValue?: Prisma.IntWithAggregatesFilter<"MilestoneProgress"> | number
  isAchieved?: Prisma.BoolWithAggregatesFilter<"MilestoneProgress"> | boolean
  achievedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"MilestoneProgress"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MilestoneProgress"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MilestoneProgress"> | Date | string
}

export type MilestoneProgressCreateInput = {
  id?: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  milestone: Prisma.MilestoneCreateNestedOneWithoutParticipantProgressInput
  participant: Prisma.ChallengeParticipantCreateNestedOneWithoutMilestoneProgressInput
}

export type MilestoneProgressUncheckedCreateInput = {
  id?: string
  milestoneId: string
  participantId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  milestone?: Prisma.MilestoneUpdateOneRequiredWithoutParticipantProgressNestedInput
  participant?: Prisma.ChallengeParticipantUpdateOneRequiredWithoutMilestoneProgressNestedInput
}

export type MilestoneProgressUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  milestoneId?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressCreateManyInput = {
  id?: string
  milestoneId: string
  participantId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  milestoneId?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressListRelationFilter = {
  every?: Prisma.MilestoneProgressWhereInput
  some?: Prisma.MilestoneProgressWhereInput
  none?: Prisma.MilestoneProgressWhereInput
}

export type MilestoneProgressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MilestoneProgressMilestoneIdParticipantIdCompoundUniqueInput = {
  milestoneId: string
  participantId: string
}

export type MilestoneProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  milestoneId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  isAchieved?: Prisma.SortOrder
  achievedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MilestoneProgressAvgOrderByAggregateInput = {
  currentValue?: Prisma.SortOrder
}

export type MilestoneProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  milestoneId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  isAchieved?: Prisma.SortOrder
  achievedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MilestoneProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  milestoneId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  isAchieved?: Prisma.SortOrder
  achievedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MilestoneProgressSumOrderByAggregateInput = {
  currentValue?: Prisma.SortOrder
}

export type MilestoneProgressCreateNestedManyWithoutMilestoneInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput> | Prisma.MilestoneProgressCreateWithoutMilestoneInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput | Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput[]
  createMany?: Prisma.MilestoneProgressCreateManyMilestoneInputEnvelope
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
}

export type MilestoneProgressUncheckedCreateNestedManyWithoutMilestoneInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput> | Prisma.MilestoneProgressCreateWithoutMilestoneInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput | Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput[]
  createMany?: Prisma.MilestoneProgressCreateManyMilestoneInputEnvelope
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
}

export type MilestoneProgressUpdateManyWithoutMilestoneNestedInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput> | Prisma.MilestoneProgressCreateWithoutMilestoneInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput | Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput[]
  upsert?: Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutMilestoneInput | Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutMilestoneInput[]
  createMany?: Prisma.MilestoneProgressCreateManyMilestoneInputEnvelope
  set?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  disconnect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  delete?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  update?: Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutMilestoneInput | Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutMilestoneInput[]
  updateMany?: Prisma.MilestoneProgressUpdateManyWithWhereWithoutMilestoneInput | Prisma.MilestoneProgressUpdateManyWithWhereWithoutMilestoneInput[]
  deleteMany?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
}

export type MilestoneProgressUncheckedUpdateManyWithoutMilestoneNestedInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput> | Prisma.MilestoneProgressCreateWithoutMilestoneInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput | Prisma.MilestoneProgressCreateOrConnectWithoutMilestoneInput[]
  upsert?: Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutMilestoneInput | Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutMilestoneInput[]
  createMany?: Prisma.MilestoneProgressCreateManyMilestoneInputEnvelope
  set?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  disconnect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  delete?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  update?: Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutMilestoneInput | Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutMilestoneInput[]
  updateMany?: Prisma.MilestoneProgressUpdateManyWithWhereWithoutMilestoneInput | Prisma.MilestoneProgressUpdateManyWithWhereWithoutMilestoneInput[]
  deleteMany?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
}

export type MilestoneProgressCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput> | Prisma.MilestoneProgressCreateWithoutParticipantInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput | Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.MilestoneProgressCreateManyParticipantInputEnvelope
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
}

export type MilestoneProgressUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput> | Prisma.MilestoneProgressCreateWithoutParticipantInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput | Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.MilestoneProgressCreateManyParticipantInputEnvelope
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
}

export type MilestoneProgressUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput> | Prisma.MilestoneProgressCreateWithoutParticipantInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput | Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutParticipantInput | Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.MilestoneProgressCreateManyParticipantInputEnvelope
  set?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  disconnect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  delete?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  update?: Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutParticipantInput | Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.MilestoneProgressUpdateManyWithWhereWithoutParticipantInput | Prisma.MilestoneProgressUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
}

export type MilestoneProgressUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput> | Prisma.MilestoneProgressCreateWithoutParticipantInput[] | Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput | Prisma.MilestoneProgressCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutParticipantInput | Prisma.MilestoneProgressUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.MilestoneProgressCreateManyParticipantInputEnvelope
  set?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  disconnect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  delete?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  connect?: Prisma.MilestoneProgressWhereUniqueInput | Prisma.MilestoneProgressWhereUniqueInput[]
  update?: Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutParticipantInput | Prisma.MilestoneProgressUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.MilestoneProgressUpdateManyWithWhereWithoutParticipantInput | Prisma.MilestoneProgressUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
}

export type MilestoneProgressCreateWithoutMilestoneInput = {
  id?: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  participant: Prisma.ChallengeParticipantCreateNestedOneWithoutMilestoneProgressInput
}

export type MilestoneProgressUncheckedCreateWithoutMilestoneInput = {
  id?: string
  participantId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressCreateOrConnectWithoutMilestoneInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput>
}

export type MilestoneProgressCreateManyMilestoneInputEnvelope = {
  data: Prisma.MilestoneProgressCreateManyMilestoneInput | Prisma.MilestoneProgressCreateManyMilestoneInput[]
  skipDuplicates?: boolean
}

export type MilestoneProgressUpsertWithWhereUniqueWithoutMilestoneInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.MilestoneProgressUpdateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedUpdateWithoutMilestoneInput>
  create: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedCreateWithoutMilestoneInput>
}

export type MilestoneProgressUpdateWithWhereUniqueWithoutMilestoneInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateWithoutMilestoneInput, Prisma.MilestoneProgressUncheckedUpdateWithoutMilestoneInput>
}

export type MilestoneProgressUpdateManyWithWhereWithoutMilestoneInput = {
  where: Prisma.MilestoneProgressScalarWhereInput
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateManyMutationInput, Prisma.MilestoneProgressUncheckedUpdateManyWithoutMilestoneInput>
}

export type MilestoneProgressScalarWhereInput = {
  AND?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
  OR?: Prisma.MilestoneProgressScalarWhereInput[]
  NOT?: Prisma.MilestoneProgressScalarWhereInput | Prisma.MilestoneProgressScalarWhereInput[]
  id?: Prisma.UuidFilter<"MilestoneProgress"> | string
  milestoneId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  participantId?: Prisma.UuidFilter<"MilestoneProgress"> | string
  currentValue?: Prisma.IntFilter<"MilestoneProgress"> | number
  isAchieved?: Prisma.BoolFilter<"MilestoneProgress"> | boolean
  achievedAt?: Prisma.DateTimeNullableFilter<"MilestoneProgress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MilestoneProgress"> | Date | string
}

export type MilestoneProgressCreateWithoutParticipantInput = {
  id?: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  milestone: Prisma.MilestoneCreateNestedOneWithoutParticipantProgressInput
}

export type MilestoneProgressUncheckedCreateWithoutParticipantInput = {
  id?: string
  milestoneId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressCreateOrConnectWithoutParticipantInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput>
}

export type MilestoneProgressCreateManyParticipantInputEnvelope = {
  data: Prisma.MilestoneProgressCreateManyParticipantInput | Prisma.MilestoneProgressCreateManyParticipantInput[]
  skipDuplicates?: boolean
}

export type MilestoneProgressUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.MilestoneProgressUpdateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.MilestoneProgressCreateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedCreateWithoutParticipantInput>
}

export type MilestoneProgressUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.MilestoneProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateWithoutParticipantInput, Prisma.MilestoneProgressUncheckedUpdateWithoutParticipantInput>
}

export type MilestoneProgressUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.MilestoneProgressScalarWhereInput
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateManyMutationInput, Prisma.MilestoneProgressUncheckedUpdateManyWithoutParticipantInput>
}

export type MilestoneProgressCreateManyMilestoneInput = {
  id?: string
  participantId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressUpdateWithoutMilestoneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ChallengeParticipantUpdateOneRequiredWithoutMilestoneProgressNestedInput
}

export type MilestoneProgressUncheckedUpdateWithoutMilestoneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressUncheckedUpdateManyWithoutMilestoneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressCreateManyParticipantInput = {
  id?: string
  milestoneId: string
  currentValue?: number
  isAchieved?: boolean
  achievedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MilestoneProgressUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  milestone?: Prisma.MilestoneUpdateOneRequiredWithoutParticipantProgressNestedInput
}

export type MilestoneProgressUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  milestoneId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MilestoneProgressUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  milestoneId?: Prisma.StringFieldUpdateOperationsInput | string
  currentValue?: Prisma.IntFieldUpdateOperationsInput | number
  isAchieved?: Prisma.BoolFieldUpdateOperationsInput | boolean
  achievedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MilestoneProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  milestoneId?: boolean
  participantId?: boolean
  currentValue?: boolean
  isAchieved?: boolean
  achievedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["milestoneProgress"]>

export type MilestoneProgressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  milestoneId?: boolean
  participantId?: boolean
  currentValue?: boolean
  isAchieved?: boolean
  achievedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["milestoneProgress"]>

export type MilestoneProgressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  milestoneId?: boolean
  participantId?: boolean
  currentValue?: boolean
  isAchieved?: boolean
  achievedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["milestoneProgress"]>

export type MilestoneProgressSelectScalar = {
  id?: boolean
  milestoneId?: boolean
  participantId?: boolean
  currentValue?: boolean
  isAchieved?: boolean
  achievedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MilestoneProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "milestoneId" | "participantId" | "currentValue" | "isAchieved" | "achievedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["milestoneProgress"]>
export type MilestoneProgressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}
export type MilestoneProgressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}
export type MilestoneProgressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  milestone?: boolean | Prisma.MilestoneDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ChallengeParticipantDefaultArgs<ExtArgs>
}

export type $MilestoneProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MilestoneProgress"
  objects: {
    milestone: Prisma.$MilestonePayload<ExtArgs>
    participant: Prisma.$ChallengeParticipantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    milestoneId: string
    participantId: string
    currentValue: number
    isAchieved: boolean
    achievedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["milestoneProgress"]>
  composites: {}
}

export type MilestoneProgressGetPayload<S extends boolean | null | undefined | MilestoneProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload, S>

export type MilestoneProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MilestoneProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MilestoneProgressCountAggregateInputType | true
  }

export interface MilestoneProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MilestoneProgress'], meta: { name: 'MilestoneProgress' } }
  /**
   * Find zero or one MilestoneProgress that matches the filter.
   * @param {MilestoneProgressFindUniqueArgs} args - Arguments to find a MilestoneProgress
   * @example
   * // Get one MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MilestoneProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, MilestoneProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MilestoneProgress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MilestoneProgressFindUniqueOrThrowArgs} args - Arguments to find a MilestoneProgress
   * @example
   * // Get one MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MilestoneProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MilestoneProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MilestoneProgress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressFindFirstArgs} args - Arguments to find a MilestoneProgress
   * @example
   * // Get one MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MilestoneProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MilestoneProgress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressFindFirstOrThrowArgs} args - Arguments to find a MilestoneProgress
   * @example
   * // Get one MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MilestoneProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MilestoneProgresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MilestoneProgresses
   * const milestoneProgresses = await prisma.milestoneProgress.findMany()
   * 
   * // Get first 10 MilestoneProgresses
   * const milestoneProgresses = await prisma.milestoneProgress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const milestoneProgressWithIdOnly = await prisma.milestoneProgress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MilestoneProgressFindManyArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MilestoneProgress.
   * @param {MilestoneProgressCreateArgs} args - Arguments to create a MilestoneProgress.
   * @example
   * // Create one MilestoneProgress
   * const MilestoneProgress = await prisma.milestoneProgress.create({
   *   data: {
   *     // ... data to create a MilestoneProgress
   *   }
   * })
   * 
   */
  create<T extends MilestoneProgressCreateArgs>(args: Prisma.SelectSubset<T, MilestoneProgressCreateArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MilestoneProgresses.
   * @param {MilestoneProgressCreateManyArgs} args - Arguments to create many MilestoneProgresses.
   * @example
   * // Create many MilestoneProgresses
   * const milestoneProgress = await prisma.milestoneProgress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MilestoneProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MilestoneProgresses and returns the data saved in the database.
   * @param {MilestoneProgressCreateManyAndReturnArgs} args - Arguments to create many MilestoneProgresses.
   * @example
   * // Create many MilestoneProgresses
   * const milestoneProgress = await prisma.milestoneProgress.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MilestoneProgresses and only return the `id`
   * const milestoneProgressWithIdOnly = await prisma.milestoneProgress.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MilestoneProgressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MilestoneProgress.
   * @param {MilestoneProgressDeleteArgs} args - Arguments to delete one MilestoneProgress.
   * @example
   * // Delete one MilestoneProgress
   * const MilestoneProgress = await prisma.milestoneProgress.delete({
   *   where: {
   *     // ... filter to delete one MilestoneProgress
   *   }
   * })
   * 
   */
  delete<T extends MilestoneProgressDeleteArgs>(args: Prisma.SelectSubset<T, MilestoneProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MilestoneProgress.
   * @param {MilestoneProgressUpdateArgs} args - Arguments to update one MilestoneProgress.
   * @example
   * // Update one MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MilestoneProgressUpdateArgs>(args: Prisma.SelectSubset<T, MilestoneProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MilestoneProgresses.
   * @param {MilestoneProgressDeleteManyArgs} args - Arguments to filter MilestoneProgresses to delete.
   * @example
   * // Delete a few MilestoneProgresses
   * const { count } = await prisma.milestoneProgress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MilestoneProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, MilestoneProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MilestoneProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MilestoneProgresses
   * const milestoneProgress = await prisma.milestoneProgress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MilestoneProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, MilestoneProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MilestoneProgresses and returns the data updated in the database.
   * @param {MilestoneProgressUpdateManyAndReturnArgs} args - Arguments to update many MilestoneProgresses.
   * @example
   * // Update many MilestoneProgresses
   * const milestoneProgress = await prisma.milestoneProgress.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MilestoneProgresses and only return the `id`
   * const milestoneProgressWithIdOnly = await prisma.milestoneProgress.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MilestoneProgressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MilestoneProgressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MilestoneProgress.
   * @param {MilestoneProgressUpsertArgs} args - Arguments to update or create a MilestoneProgress.
   * @example
   * // Update or create a MilestoneProgress
   * const milestoneProgress = await prisma.milestoneProgress.upsert({
   *   create: {
   *     // ... data to create a MilestoneProgress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MilestoneProgress we want to update
   *   }
   * })
   */
  upsert<T extends MilestoneProgressUpsertArgs>(args: Prisma.SelectSubset<T, MilestoneProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__MilestoneProgressClient<runtime.Types.Result.GetResult<Prisma.$MilestoneProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MilestoneProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressCountArgs} args - Arguments to filter MilestoneProgresses to count.
   * @example
   * // Count the number of MilestoneProgresses
   * const count = await prisma.milestoneProgress.count({
   *   where: {
   *     // ... the filter for the MilestoneProgresses we want to count
   *   }
   * })
  **/
  count<T extends MilestoneProgressCountArgs>(
    args?: Prisma.Subset<T, MilestoneProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MilestoneProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MilestoneProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MilestoneProgressAggregateArgs>(args: Prisma.Subset<T, MilestoneProgressAggregateArgs>): Prisma.PrismaPromise<GetMilestoneProgressAggregateType<T>>

  /**
   * Group by MilestoneProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MilestoneProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MilestoneProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MilestoneProgressGroupByArgs['orderBy'] }
      : { orderBy?: MilestoneProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MilestoneProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMilestoneProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MilestoneProgress model
 */
readonly fields: MilestoneProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MilestoneProgress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MilestoneProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  milestone<T extends Prisma.MilestoneDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MilestoneDefaultArgs<ExtArgs>>): Prisma.Prisma__MilestoneClient<runtime.Types.Result.GetResult<Prisma.$MilestonePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  participant<T extends Prisma.ChallengeParticipantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChallengeParticipantDefaultArgs<ExtArgs>>): Prisma.Prisma__ChallengeParticipantClient<runtime.Types.Result.GetResult<Prisma.$ChallengeParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MilestoneProgress model
 */
export interface MilestoneProgressFieldRefs {
  readonly id: Prisma.FieldRef<"MilestoneProgress", 'String'>
  readonly milestoneId: Prisma.FieldRef<"MilestoneProgress", 'String'>
  readonly participantId: Prisma.FieldRef<"MilestoneProgress", 'String'>
  readonly currentValue: Prisma.FieldRef<"MilestoneProgress", 'Int'>
  readonly isAchieved: Prisma.FieldRef<"MilestoneProgress", 'Boolean'>
  readonly achievedAt: Prisma.FieldRef<"MilestoneProgress", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"MilestoneProgress", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MilestoneProgress", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MilestoneProgress findUnique
 */
export type MilestoneProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter, which MilestoneProgress to fetch.
   */
  where: Prisma.MilestoneProgressWhereUniqueInput
}

/**
 * MilestoneProgress findUniqueOrThrow
 */
export type MilestoneProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter, which MilestoneProgress to fetch.
   */
  where: Prisma.MilestoneProgressWhereUniqueInput
}

/**
 * MilestoneProgress findFirst
 */
export type MilestoneProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter, which MilestoneProgress to fetch.
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MilestoneProgresses to fetch.
   */
  orderBy?: Prisma.MilestoneProgressOrderByWithRelationInput | Prisma.MilestoneProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MilestoneProgresses.
   */
  cursor?: Prisma.MilestoneProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MilestoneProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MilestoneProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MilestoneProgresses.
   */
  distinct?: Prisma.MilestoneProgressScalarFieldEnum | Prisma.MilestoneProgressScalarFieldEnum[]
}

/**
 * MilestoneProgress findFirstOrThrow
 */
export type MilestoneProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter, which MilestoneProgress to fetch.
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MilestoneProgresses to fetch.
   */
  orderBy?: Prisma.MilestoneProgressOrderByWithRelationInput | Prisma.MilestoneProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MilestoneProgresses.
   */
  cursor?: Prisma.MilestoneProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MilestoneProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MilestoneProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MilestoneProgresses.
   */
  distinct?: Prisma.MilestoneProgressScalarFieldEnum | Prisma.MilestoneProgressScalarFieldEnum[]
}

/**
 * MilestoneProgress findMany
 */
export type MilestoneProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter, which MilestoneProgresses to fetch.
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MilestoneProgresses to fetch.
   */
  orderBy?: Prisma.MilestoneProgressOrderByWithRelationInput | Prisma.MilestoneProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MilestoneProgresses.
   */
  cursor?: Prisma.MilestoneProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MilestoneProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MilestoneProgresses.
   */
  skip?: number
  distinct?: Prisma.MilestoneProgressScalarFieldEnum | Prisma.MilestoneProgressScalarFieldEnum[]
}

/**
 * MilestoneProgress create
 */
export type MilestoneProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * The data needed to create a MilestoneProgress.
   */
  data: Prisma.XOR<Prisma.MilestoneProgressCreateInput, Prisma.MilestoneProgressUncheckedCreateInput>
}

/**
 * MilestoneProgress createMany
 */
export type MilestoneProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MilestoneProgresses.
   */
  data: Prisma.MilestoneProgressCreateManyInput | Prisma.MilestoneProgressCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MilestoneProgress createManyAndReturn
 */
export type MilestoneProgressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * The data used to create many MilestoneProgresses.
   */
  data: Prisma.MilestoneProgressCreateManyInput | Prisma.MilestoneProgressCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MilestoneProgress update
 */
export type MilestoneProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * The data needed to update a MilestoneProgress.
   */
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateInput, Prisma.MilestoneProgressUncheckedUpdateInput>
  /**
   * Choose, which MilestoneProgress to update.
   */
  where: Prisma.MilestoneProgressWhereUniqueInput
}

/**
 * MilestoneProgress updateMany
 */
export type MilestoneProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MilestoneProgresses.
   */
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateManyMutationInput, Prisma.MilestoneProgressUncheckedUpdateManyInput>
  /**
   * Filter which MilestoneProgresses to update
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * Limit how many MilestoneProgresses to update.
   */
  limit?: number
}

/**
 * MilestoneProgress updateManyAndReturn
 */
export type MilestoneProgressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * The data used to update MilestoneProgresses.
   */
  data: Prisma.XOR<Prisma.MilestoneProgressUpdateManyMutationInput, Prisma.MilestoneProgressUncheckedUpdateManyInput>
  /**
   * Filter which MilestoneProgresses to update
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * Limit how many MilestoneProgresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MilestoneProgress upsert
 */
export type MilestoneProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * The filter to search for the MilestoneProgress to update in case it exists.
   */
  where: Prisma.MilestoneProgressWhereUniqueInput
  /**
   * In case the MilestoneProgress found by the `where` argument doesn't exist, create a new MilestoneProgress with this data.
   */
  create: Prisma.XOR<Prisma.MilestoneProgressCreateInput, Prisma.MilestoneProgressUncheckedCreateInput>
  /**
   * In case the MilestoneProgress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MilestoneProgressUpdateInput, Prisma.MilestoneProgressUncheckedUpdateInput>
}

/**
 * MilestoneProgress delete
 */
export type MilestoneProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
  /**
   * Filter which MilestoneProgress to delete.
   */
  where: Prisma.MilestoneProgressWhereUniqueInput
}

/**
 * MilestoneProgress deleteMany
 */
export type MilestoneProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MilestoneProgresses to delete
   */
  where?: Prisma.MilestoneProgressWhereInput
  /**
   * Limit how many MilestoneProgresses to delete.
   */
  limit?: number
}

/**
 * MilestoneProgress without action
 */
export type MilestoneProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MilestoneProgress
   */
  select?: Prisma.MilestoneProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MilestoneProgress
   */
  omit?: Prisma.MilestoneProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneProgressInclude<ExtArgs> | null
}
