
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Profile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Profile
 * 
 */
export type ProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfilePayload>

export type AggregateProfile = {
  _count: ProfileCountAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

export type ProfileMinAggregateOutputType = {
  id: string | null
  username: string | null
  avatarUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfileMaxAggregateOutputType = {
  id: string | null
  username: string | null
  avatarUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfileCountAggregateOutputType = {
  id: number
  username: number
  avatarUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProfileMinAggregateInputType = {
  id?: true
  username?: true
  avatarUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfileMaxAggregateInputType = {
  id?: true
  username?: true
  avatarUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfileCountAggregateInputType = {
  id?: true
  username?: true
  avatarUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profile to aggregate.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Profiles
  **/
  _count?: true | ProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileMaxAggregateInputType
}

export type GetProfileAggregateType<T extends ProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateProfile[P]>
}




export type ProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithAggregationInput | Prisma.ProfileOrderByWithAggregationInput[]
  by: Prisma.ProfileScalarFieldEnum[] | Prisma.ProfileScalarFieldEnum
  having?: Prisma.ProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileCountAggregateInputType | true
  _min?: ProfileMinAggregateInputType
  _max?: ProfileMaxAggregateInputType
}

export type ProfileGroupByOutputType = {
  id: string
  username: string | null
  avatarUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProfileCountAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

type GetProfileGroupByPayload<T extends ProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
      }
    >
  > 



export type ProfileWhereInput = {
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  id?: Prisma.UuidFilter<"Profile"> | string
  username?: Prisma.StringNullableFilter<"Profile"> | string | null
  avatarUrl?: Prisma.StringNullableFilter<"Profile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  createdTeams?: Prisma.TeamListRelationFilter
  teamMemberships?: Prisma.TeamMembershipListRelationFilter
  createdChallenges?: Prisma.ChallengeListRelationFilter
  challengeEntries?: Prisma.ChallengeParticipantListRelationFilter
  activities?: Prisma.ActivityListRelationFilter
  posts?: Prisma.PostListRelationFilter
  comments?: Prisma.CommentListRelationFilter
}

export type ProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  avatarUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdTeams?: Prisma.TeamOrderByRelationAggregateInput
  teamMemberships?: Prisma.TeamMembershipOrderByRelationAggregateInput
  createdChallenges?: Prisma.ChallengeOrderByRelationAggregateInput
  challengeEntries?: Prisma.ChallengeParticipantOrderByRelationAggregateInput
  activities?: Prisma.ActivityOrderByRelationAggregateInput
  posts?: Prisma.PostOrderByRelationAggregateInput
  comments?: Prisma.CommentOrderByRelationAggregateInput
}

export type ProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  username?: string
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  avatarUrl?: Prisma.StringNullableFilter<"Profile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  createdTeams?: Prisma.TeamListRelationFilter
  teamMemberships?: Prisma.TeamMembershipListRelationFilter
  createdChallenges?: Prisma.ChallengeListRelationFilter
  challengeEntries?: Prisma.ChallengeParticipantListRelationFilter
  activities?: Prisma.ActivityListRelationFilter
  posts?: Prisma.PostListRelationFilter
  comments?: Prisma.CommentListRelationFilter
}, "id" | "username">

export type ProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  avatarUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProfileCountOrderByAggregateInput
  _max?: Prisma.ProfileMaxOrderByAggregateInput
  _min?: Prisma.ProfileMinOrderByAggregateInput
}

export type ProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Profile"> | string
  username?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  avatarUrl?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Profile"> | Date | string
}

export type ProfileCreateInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateManyInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileScalarRelationFilter = {
  is?: Prisma.ProfileWhereInput
  isNot?: Prisma.ProfileWhereInput
}

export type ProfileNullableScalarRelationFilter = {
  is?: Prisma.ProfileWhereInput | null
  isNot?: Prisma.ProfileWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ProfileCreateNestedOneWithoutCreatedTeamsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedCreateWithoutCreatedTeamsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCreatedTeamsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutCreatedTeamsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedCreateWithoutCreatedTeamsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCreatedTeamsInput
  upsert?: Prisma.ProfileUpsertWithoutCreatedTeamsInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutCreatedTeamsInput, Prisma.ProfileUpdateWithoutCreatedTeamsInput>, Prisma.ProfileUncheckedUpdateWithoutCreatedTeamsInput>
}

export type ProfileCreateNestedOneWithoutTeamMembershipsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedCreateWithoutTeamMembershipsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutTeamMembershipsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutTeamMembershipsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedCreateWithoutTeamMembershipsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutTeamMembershipsInput
  upsert?: Prisma.ProfileUpsertWithoutTeamMembershipsInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutTeamMembershipsInput, Prisma.ProfileUpdateWithoutTeamMembershipsInput>, Prisma.ProfileUncheckedUpdateWithoutTeamMembershipsInput>
}

export type ProfileCreateNestedOneWithoutCreatedChallengesInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedCreateWithoutCreatedChallengesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCreatedChallengesInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutCreatedChallengesNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedCreateWithoutCreatedChallengesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCreatedChallengesInput
  upsert?: Prisma.ProfileUpsertWithoutCreatedChallengesInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutCreatedChallengesInput, Prisma.ProfileUpdateWithoutCreatedChallengesInput>, Prisma.ProfileUncheckedUpdateWithoutCreatedChallengesInput>
}

export type ProfileCreateNestedOneWithoutChallengeEntriesInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedCreateWithoutChallengeEntriesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutChallengeEntriesInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutChallengeEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedCreateWithoutChallengeEntriesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutChallengeEntriesInput
  upsert?: Prisma.ProfileUpsertWithoutChallengeEntriesInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutChallengeEntriesInput, Prisma.ProfileUpdateWithoutChallengeEntriesInput>, Prisma.ProfileUncheckedUpdateWithoutChallengeEntriesInput>
}

export type ProfileCreateNestedOneWithoutActivitiesInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutActivitiesInput, Prisma.ProfileUncheckedCreateWithoutActivitiesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutActivitiesInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutActivitiesNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutActivitiesInput, Prisma.ProfileUncheckedCreateWithoutActivitiesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutActivitiesInput
  upsert?: Prisma.ProfileUpsertWithoutActivitiesInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutActivitiesInput, Prisma.ProfileUpdateWithoutActivitiesInput>, Prisma.ProfileUncheckedUpdateWithoutActivitiesInput>
}

export type ProfileCreateNestedOneWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutPostsInput, Prisma.ProfileUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutPostsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutPostsInput, Prisma.ProfileUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutPostsInput
  upsert?: Prisma.ProfileUpsertWithoutPostsInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutPostsInput, Prisma.ProfileUpdateWithoutPostsInput>, Prisma.ProfileUncheckedUpdateWithoutPostsInput>
}

export type ProfileCreateNestedOneWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCommentsInput, Prisma.ProfileUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCommentsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneRequiredWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutCommentsInput, Prisma.ProfileUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutCommentsInput
  upsert?: Prisma.ProfileUpsertWithoutCommentsInput
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutCommentsInput, Prisma.ProfileUpdateWithoutCommentsInput>, Prisma.ProfileUncheckedUpdateWithoutCommentsInput>
}

export type ProfileCreateWithoutCreatedTeamsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutCreatedTeamsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutCreatedTeamsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedCreateWithoutCreatedTeamsInput>
}

export type ProfileUpsertWithoutCreatedTeamsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedUpdateWithoutCreatedTeamsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedCreateWithoutCreatedTeamsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutCreatedTeamsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutCreatedTeamsInput, Prisma.ProfileUncheckedUpdateWithoutCreatedTeamsInput>
}

export type ProfileUpdateWithoutCreatedTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutCreatedTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutTeamMembershipsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutTeamMembershipsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutTeamMembershipsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedCreateWithoutTeamMembershipsInput>
}

export type ProfileUpsertWithoutTeamMembershipsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedUpdateWithoutTeamMembershipsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedCreateWithoutTeamMembershipsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutTeamMembershipsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutTeamMembershipsInput, Prisma.ProfileUncheckedUpdateWithoutTeamMembershipsInput>
}

export type ProfileUpdateWithoutTeamMembershipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutTeamMembershipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutCreatedChallengesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutCreatedChallengesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutCreatedChallengesInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedCreateWithoutCreatedChallengesInput>
}

export type ProfileUpsertWithoutCreatedChallengesInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedUpdateWithoutCreatedChallengesInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedCreateWithoutCreatedChallengesInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutCreatedChallengesInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutCreatedChallengesInput, Prisma.ProfileUncheckedUpdateWithoutCreatedChallengesInput>
}

export type ProfileUpdateWithoutCreatedChallengesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutCreatedChallengesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutChallengeEntriesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutChallengeEntriesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutChallengeEntriesInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedCreateWithoutChallengeEntriesInput>
}

export type ProfileUpsertWithoutChallengeEntriesInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedUpdateWithoutChallengeEntriesInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedCreateWithoutChallengeEntriesInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutChallengeEntriesInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutChallengeEntriesInput, Prisma.ProfileUncheckedUpdateWithoutChallengeEntriesInput>
}

export type ProfileUpdateWithoutChallengeEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutChallengeEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutActivitiesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutActivitiesInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutActivitiesInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutActivitiesInput, Prisma.ProfileUncheckedCreateWithoutActivitiesInput>
}

export type ProfileUpsertWithoutActivitiesInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutActivitiesInput, Prisma.ProfileUncheckedUpdateWithoutActivitiesInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutActivitiesInput, Prisma.ProfileUncheckedCreateWithoutActivitiesInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutActivitiesInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutActivitiesInput, Prisma.ProfileUncheckedUpdateWithoutActivitiesInput>
}

export type ProfileUpdateWithoutActivitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutActivitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutPostsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentCreateNestedManyWithoutAuthorInput
}

export type ProfileUncheckedCreateWithoutPostsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutAuthorInput
}

export type ProfileCreateOrConnectWithoutPostsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutPostsInput, Prisma.ProfileUncheckedCreateWithoutPostsInput>
}

export type ProfileUpsertWithoutPostsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutPostsInput, Prisma.ProfileUncheckedUpdateWithoutPostsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutPostsInput, Prisma.ProfileUncheckedCreateWithoutPostsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutPostsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutPostsInput, Prisma.ProfileUncheckedUpdateWithoutPostsInput>
}

export type ProfileUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUpdateManyWithoutAuthorNestedInput
}

export type ProfileUncheckedUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutAuthorNestedInput
}

export type ProfileCreateWithoutCommentsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutCommentsInput = {
  id: string
  username?: string | null
  avatarUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  createdTeams?: Prisma.TeamUncheckedCreateNestedManyWithoutCreatorInput
  teamMemberships?: Prisma.TeamMembershipUncheckedCreateNestedManyWithoutUserInput
  createdChallenges?: Prisma.ChallengeUncheckedCreateNestedManyWithoutCreatorInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedCreateNestedManyWithoutUserInput
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutProfileInput
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutCommentsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCommentsInput, Prisma.ProfileUncheckedCreateWithoutCommentsInput>
}

export type ProfileUpsertWithoutCommentsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutCommentsInput, Prisma.ProfileUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutCommentsInput, Prisma.ProfileUncheckedCreateWithoutCommentsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutCommentsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutCommentsInput, Prisma.ProfileUncheckedUpdateWithoutCommentsInput>
}

export type ProfileUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdTeams?: Prisma.TeamUncheckedUpdateManyWithoutCreatorNestedInput
  teamMemberships?: Prisma.TeamMembershipUncheckedUpdateManyWithoutUserNestedInput
  createdChallenges?: Prisma.ChallengeUncheckedUpdateManyWithoutCreatorNestedInput
  challengeEntries?: Prisma.ChallengeParticipantUncheckedUpdateManyWithoutUserNestedInput
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutProfileNestedInput
  posts?: Prisma.PostUncheckedUpdateManyWithoutProfileNestedInput
}


/**
 * Count Type ProfileCountOutputType
 */

export type ProfileCountOutputType = {
  createdTeams: number
  teamMemberships: number
  createdChallenges: number
  challengeEntries: number
  activities: number
  posts: number
  comments: number
}

export type ProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdTeams?: boolean | ProfileCountOutputTypeCountCreatedTeamsArgs
  teamMemberships?: boolean | ProfileCountOutputTypeCountTeamMembershipsArgs
  createdChallenges?: boolean | ProfileCountOutputTypeCountCreatedChallengesArgs
  challengeEntries?: boolean | ProfileCountOutputTypeCountChallengeEntriesArgs
  activities?: boolean | ProfileCountOutputTypeCountActivitiesArgs
  posts?: boolean | ProfileCountOutputTypeCountPostsArgs
  comments?: boolean | ProfileCountOutputTypeCountCommentsArgs
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileCountOutputType
   */
  select?: Prisma.ProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountCreatedTeamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountTeamMembershipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamMembershipWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountCreatedChallengesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChallengeWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountChallengeEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChallengeParticipantWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountActivitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountCommentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommentWhereInput
}


export type ProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  avatarUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdTeams?: boolean | Prisma.Profile$createdTeamsArgs<ExtArgs>
  teamMemberships?: boolean | Prisma.Profile$teamMembershipsArgs<ExtArgs>
  createdChallenges?: boolean | Prisma.Profile$createdChallengesArgs<ExtArgs>
  challengeEntries?: boolean | Prisma.Profile$challengeEntriesArgs<ExtArgs>
  activities?: boolean | Prisma.Profile$activitiesArgs<ExtArgs>
  posts?: boolean | Prisma.Profile$postsArgs<ExtArgs>
  comments?: boolean | Prisma.Profile$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profile"]>

export type ProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  avatarUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["profile"]>

export type ProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  avatarUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["profile"]>

export type ProfileSelectScalar = {
  id?: boolean
  username?: boolean
  avatarUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "avatarUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["profile"]>
export type ProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdTeams?: boolean | Prisma.Profile$createdTeamsArgs<ExtArgs>
  teamMemberships?: boolean | Prisma.Profile$teamMembershipsArgs<ExtArgs>
  createdChallenges?: boolean | Prisma.Profile$createdChallengesArgs<ExtArgs>
  challengeEntries?: boolean | Prisma.Profile$challengeEntriesArgs<ExtArgs>
  activities?: boolean | Prisma.Profile$activitiesArgs<ExtArgs>
  posts?: boolean | Prisma.Profile$postsArgs<ExtArgs>
  comments?: boolean | Prisma.Profile$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Profile"
  objects: {
    createdTeams: Prisma.$TeamPayload<ExtArgs>[]
    teamMemberships: Prisma.$TeamMembershipPayload<ExtArgs>[]
    createdChallenges: Prisma.$ChallengePayload<ExtArgs>[]
    challengeEntries: Prisma.$ChallengeParticipantPayload<ExtArgs>[]
    activities: Prisma.$ActivityPayload<ExtArgs>[]
    posts: Prisma.$PostPayload<ExtArgs>[]
    comments: Prisma.$CommentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string | null
    avatarUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["profile"]>
  composites: {}
}

export type ProfileGetPayload<S extends boolean | null | undefined | ProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfilePayload, S>

export type ProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileCountAggregateInputType | true
  }

export interface ProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Profile'], meta: { name: 'Profile' } }
  /**
   * Find zero or one Profile that matches the filter.
   * @param {ProfileFindUniqueArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Profile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileFindUniqueOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Profiles
   * const profiles = await prisma.profile.findMany()
   * 
   * // Get first 10 Profiles
   * const profiles = await prisma.profile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profileWithIdOnly = await prisma.profile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfileFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Profile.
   * @param {ProfileCreateArgs} args - Arguments to create a Profile.
   * @example
   * // Create one Profile
   * const Profile = await prisma.profile.create({
   *   data: {
   *     // ... data to create a Profile
   *   }
   * })
   * 
   */
  create<T extends ProfileCreateArgs>(args: Prisma.SelectSubset<T, ProfileCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Profiles.
   * @param {ProfileCreateManyArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profile = await prisma.profile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Profiles and returns the data saved in the database.
   * @param {ProfileCreateManyAndReturnArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profile = await prisma.profile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Profiles and only return the `id`
   * const profileWithIdOnly = await prisma.profile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Profile.
   * @param {ProfileDeleteArgs} args - Arguments to delete one Profile.
   * @example
   * // Delete one Profile
   * const Profile = await prisma.profile.delete({
   *   where: {
   *     // ... filter to delete one Profile
   *   }
   * })
   * 
   */
  delete<T extends ProfileDeleteArgs>(args: Prisma.SelectSubset<T, ProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Profile.
   * @param {ProfileUpdateArgs} args - Arguments to update one Profile.
   * @example
   * // Update one Profile
   * const profile = await prisma.profile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileUpdateArgs>(args: Prisma.SelectSubset<T, ProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Profiles.
   * @param {ProfileDeleteManyArgs} args - Arguments to filter Profiles to delete.
   * @example
   * // Delete a few Profiles
   * const { count } = await prisma.profile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Profiles
   * const profile = await prisma.profile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles and returns the data updated in the database.
   * @param {ProfileUpdateManyAndReturnArgs} args - Arguments to update many Profiles.
   * @example
   * // Update many Profiles
   * const profile = await prisma.profile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Profiles and only return the `id`
   * const profileWithIdOnly = await prisma.profile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Profile.
   * @param {ProfileUpsertArgs} args - Arguments to update or create a Profile.
   * @example
   * // Update or create a Profile
   * const profile = await prisma.profile.upsert({
   *   create: {
   *     // ... data to create a Profile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Profile we want to update
   *   }
   * })
   */
  upsert<T extends ProfileUpsertArgs>(args: Prisma.SelectSubset<T, ProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileCountArgs} args - Arguments to filter Profiles to count.
   * @example
   * // Count the number of Profiles
   * const count = await prisma.profile.count({
   *   where: {
   *     // ... the filter for the Profiles we want to count
   *   }
   * })
  **/
  count<T extends ProfileCountArgs>(
    args?: Prisma.Subset<T, ProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileAggregateArgs>(args: Prisma.Subset<T, ProfileAggregateArgs>): Prisma.PrismaPromise<GetProfileAggregateType<T>>

  /**
   * Group by Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileGroupByArgs['orderBy'] }
      : { orderBy?: ProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Profile model
 */
readonly fields: ProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Profile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdTeams<T extends Prisma.Profile$createdTeamsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$createdTeamsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  teamMemberships<T extends Prisma.Profile$teamMembershipsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$teamMembershipsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamMembershipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdChallenges<T extends Prisma.Profile$createdChallengesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$createdChallengesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChallengePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  challengeEntries<T extends Prisma.Profile$challengeEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$challengeEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChallengeParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  activities<T extends Prisma.Profile$activitiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$activitiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  posts<T extends Prisma.Profile$postsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$postsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  comments<T extends Prisma.Profile$commentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$commentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Profile model
 */
export interface ProfileFieldRefs {
  readonly id: Prisma.FieldRef<"Profile", 'String'>
  readonly username: Prisma.FieldRef<"Profile", 'String'>
  readonly avatarUrl: Prisma.FieldRef<"Profile", 'String'>
  readonly createdAt: Prisma.FieldRef<"Profile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Profile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Profile findUnique
 */
export type ProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findUniqueOrThrow
 */
export type ProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findFirst
 */
export type ProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findFirstOrThrow
 */
export type ProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findMany
 */
export type ProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile create
 */
export type ProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
}

/**
 * Profile createMany
 */
export type ProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfileCreateManyInput | Prisma.ProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profile createManyAndReturn
 */
export type ProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfileCreateManyInput | Prisma.ProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profile update
 */
export type ProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
  /**
   * Choose, which Profile to update.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile updateMany
 */
export type ProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
}

/**
 * Profile updateManyAndReturn
 */
export type ProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
}

/**
 * Profile upsert
 */
export type ProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the Profile to update in case it exists.
   */
  where: Prisma.ProfileWhereUniqueInput
  /**
   * In case the Profile found by the `where` argument doesn't exist, create a new Profile with this data.
   */
  create: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
  /**
   * In case the Profile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
}

/**
 * Profile delete
 */
export type ProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter which Profile to delete.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile deleteMany
 */
export type ProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profiles to delete
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to delete.
   */
  limit?: number
}

/**
 * Profile.createdTeams
 */
export type Profile$createdTeamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Team
   */
  select?: Prisma.TeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Team
   */
  omit?: Prisma.TeamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamInclude<ExtArgs> | null
  where?: Prisma.TeamWhereInput
  orderBy?: Prisma.TeamOrderByWithRelationInput | Prisma.TeamOrderByWithRelationInput[]
  cursor?: Prisma.TeamWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TeamScalarFieldEnum | Prisma.TeamScalarFieldEnum[]
}

/**
 * Profile.teamMemberships
 */
export type Profile$teamMembershipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamMembership
   */
  select?: Prisma.TeamMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamMembership
   */
  omit?: Prisma.TeamMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamMembershipInclude<ExtArgs> | null
  where?: Prisma.TeamMembershipWhereInput
  orderBy?: Prisma.TeamMembershipOrderByWithRelationInput | Prisma.TeamMembershipOrderByWithRelationInput[]
  cursor?: Prisma.TeamMembershipWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TeamMembershipScalarFieldEnum | Prisma.TeamMembershipScalarFieldEnum[]
}

/**
 * Profile.createdChallenges
 */
export type Profile$createdChallengesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Challenge
   */
  select?: Prisma.ChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Challenge
   */
  omit?: Prisma.ChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeInclude<ExtArgs> | null
  where?: Prisma.ChallengeWhereInput
  orderBy?: Prisma.ChallengeOrderByWithRelationInput | Prisma.ChallengeOrderByWithRelationInput[]
  cursor?: Prisma.ChallengeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChallengeScalarFieldEnum | Prisma.ChallengeScalarFieldEnum[]
}

/**
 * Profile.challengeEntries
 */
export type Profile$challengeEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChallengeParticipant
   */
  select?: Prisma.ChallengeParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChallengeParticipant
   */
  omit?: Prisma.ChallengeParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChallengeParticipantInclude<ExtArgs> | null
  where?: Prisma.ChallengeParticipantWhereInput
  orderBy?: Prisma.ChallengeParticipantOrderByWithRelationInput | Prisma.ChallengeParticipantOrderByWithRelationInput[]
  cursor?: Prisma.ChallengeParticipantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChallengeParticipantScalarFieldEnum | Prisma.ChallengeParticipantScalarFieldEnum[]
}

/**
 * Profile.activities
 */
export type Profile$activitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  where?: Prisma.ActivityWhereInput
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  cursor?: Prisma.ActivityWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Profile.posts
 */
export type Profile$postsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * Profile.comments
 */
export type Profile$commentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comment
   */
  select?: Prisma.CommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comment
   */
  omit?: Prisma.CommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommentInclude<ExtArgs> | null
  where?: Prisma.CommentWhereInput
  orderBy?: Prisma.CommentOrderByWithRelationInput | Prisma.CommentOrderByWithRelationInput[]
  cursor?: Prisma.CommentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CommentScalarFieldEnum | Prisma.CommentScalarFieldEnum[]
}

/**
 * Profile without action
 */
export type ProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
}
