
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `WorkoutComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkoutComment
 * 
 */
export type WorkoutCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkoutCommentPayload>

export type AggregateWorkoutComment = {
  _count: WorkoutCommentCountAggregateOutputType | null
  _min: WorkoutCommentMinAggregateOutputType | null
  _max: WorkoutCommentMaxAggregateOutputType | null
}

export type WorkoutCommentMinAggregateOutputType = {
  id: string | null
  authorId: string | null
  workoutId: string | null
  content: string | null
  createdAt: Date | null
}

export type WorkoutCommentMaxAggregateOutputType = {
  id: string | null
  authorId: string | null
  workoutId: string | null
  content: string | null
  createdAt: Date | null
}

export type WorkoutCommentCountAggregateOutputType = {
  id: number
  authorId: number
  workoutId: number
  content: number
  createdAt: number
  _all: number
}


export type WorkoutCommentMinAggregateInputType = {
  id?: true
  authorId?: true
  workoutId?: true
  content?: true
  createdAt?: true
}

export type WorkoutCommentMaxAggregateInputType = {
  id?: true
  authorId?: true
  workoutId?: true
  content?: true
  createdAt?: true
}

export type WorkoutCommentCountAggregateInputType = {
  id?: true
  authorId?: true
  workoutId?: true
  content?: true
  createdAt?: true
  _all?: true
}

export type WorkoutCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkoutComment to aggregate.
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutComments to fetch.
   */
  orderBy?: Prisma.WorkoutCommentOrderByWithRelationInput | Prisma.WorkoutCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkoutCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkoutComments
  **/
  _count?: true | WorkoutCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkoutCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkoutCommentMaxAggregateInputType
}

export type GetWorkoutCommentAggregateType<T extends WorkoutCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkoutComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkoutComment[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkoutComment[P]>
}




export type WorkoutCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkoutCommentWhereInput
  orderBy?: Prisma.WorkoutCommentOrderByWithAggregationInput | Prisma.WorkoutCommentOrderByWithAggregationInput[]
  by: Prisma.WorkoutCommentScalarFieldEnum[] | Prisma.WorkoutCommentScalarFieldEnum
  having?: Prisma.WorkoutCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkoutCommentCountAggregateInputType | true
  _min?: WorkoutCommentMinAggregateInputType
  _max?: WorkoutCommentMaxAggregateInputType
}

export type WorkoutCommentGroupByOutputType = {
  id: string
  authorId: string
  workoutId: string
  content: string
  createdAt: Date
  _count: WorkoutCommentCountAggregateOutputType | null
  _min: WorkoutCommentMinAggregateOutputType | null
  _max: WorkoutCommentMaxAggregateOutputType | null
}

type GetWorkoutCommentGroupByPayload<T extends WorkoutCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkoutCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkoutCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkoutCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkoutCommentGroupByOutputType[P]>
      }
    >
  > 



export type WorkoutCommentWhereInput = {
  AND?: Prisma.WorkoutCommentWhereInput | Prisma.WorkoutCommentWhereInput[]
  OR?: Prisma.WorkoutCommentWhereInput[]
  NOT?: Prisma.WorkoutCommentWhereInput | Prisma.WorkoutCommentWhereInput[]
  id?: Prisma.UuidFilter<"WorkoutComment"> | string
  authorId?: Prisma.UuidFilter<"WorkoutComment"> | string
  workoutId?: Prisma.UuidFilter<"WorkoutComment"> | string
  content?: Prisma.StringFilter<"WorkoutComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutComment"> | Date | string
  author?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  workout?: Prisma.XOR<Prisma.WorkoutScalarRelationFilter, Prisma.WorkoutWhereInput>
}

export type WorkoutCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  workoutId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  author?: Prisma.ProfileOrderByWithRelationInput
  workout?: Prisma.WorkoutOrderByWithRelationInput
}

export type WorkoutCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkoutCommentWhereInput | Prisma.WorkoutCommentWhereInput[]
  OR?: Prisma.WorkoutCommentWhereInput[]
  NOT?: Prisma.WorkoutCommentWhereInput | Prisma.WorkoutCommentWhereInput[]
  authorId?: Prisma.UuidFilter<"WorkoutComment"> | string
  workoutId?: Prisma.UuidFilter<"WorkoutComment"> | string
  content?: Prisma.StringFilter<"WorkoutComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutComment"> | Date | string
  author?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
  workout?: Prisma.XOR<Prisma.WorkoutScalarRelationFilter, Prisma.WorkoutWhereInput>
}, "id">

export type WorkoutCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  workoutId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.WorkoutCommentCountOrderByAggregateInput
  _max?: Prisma.WorkoutCommentMaxOrderByAggregateInput
  _min?: Prisma.WorkoutCommentMinOrderByAggregateInput
}

export type WorkoutCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkoutCommentScalarWhereWithAggregatesInput | Prisma.WorkoutCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkoutCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkoutCommentScalarWhereWithAggregatesInput | Prisma.WorkoutCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"WorkoutComment"> | string
  authorId?: Prisma.UuidWithAggregatesFilter<"WorkoutComment"> | string
  workoutId?: Prisma.UuidWithAggregatesFilter<"WorkoutComment"> | string
  content?: Prisma.StringWithAggregatesFilter<"WorkoutComment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkoutComment"> | Date | string
}

export type WorkoutCommentCreateInput = {
  id?: string
  content: string
  createdAt?: Date | string
  author: Prisma.ProfileCreateNestedOneWithoutWorkoutCommentInput
  workout: Prisma.WorkoutCreateNestedOneWithoutCommentsInput
}

export type WorkoutCommentUncheckedCreateInput = {
  id?: string
  authorId: string
  workoutId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.ProfileUpdateOneRequiredWithoutWorkoutCommentNestedInput
  workout?: Prisma.WorkoutUpdateOneRequiredWithoutCommentsNestedInput
}

export type WorkoutCommentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  workoutId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentCreateManyInput = {
  id?: string
  authorId: string
  workoutId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  workoutId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentListRelationFilter = {
  every?: Prisma.WorkoutCommentWhereInput
  some?: Prisma.WorkoutCommentWhereInput
  none?: Prisma.WorkoutCommentWhereInput
}

export type WorkoutCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkoutCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  workoutId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  workoutId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  workoutId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutCommentCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput> | Prisma.WorkoutCommentCreateWithoutAuthorInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput | Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.WorkoutCommentCreateManyAuthorInputEnvelope
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
}

export type WorkoutCommentUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput> | Prisma.WorkoutCommentCreateWithoutAuthorInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput | Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.WorkoutCommentCreateManyAuthorInputEnvelope
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
}

export type WorkoutCommentUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput> | Prisma.WorkoutCommentCreateWithoutAuthorInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput | Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutAuthorInput | Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.WorkoutCommentCreateManyAuthorInputEnvelope
  set?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  delete?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  update?: Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutAuthorInput | Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.WorkoutCommentUpdateManyWithWhereWithoutAuthorInput | Prisma.WorkoutCommentUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
}

export type WorkoutCommentUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput> | Prisma.WorkoutCommentCreateWithoutAuthorInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput | Prisma.WorkoutCommentCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutAuthorInput | Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.WorkoutCommentCreateManyAuthorInputEnvelope
  set?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  delete?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  update?: Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutAuthorInput | Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.WorkoutCommentUpdateManyWithWhereWithoutAuthorInput | Prisma.WorkoutCommentUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
}

export type WorkoutCommentCreateNestedManyWithoutWorkoutInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput> | Prisma.WorkoutCommentCreateWithoutWorkoutInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput | Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput[]
  createMany?: Prisma.WorkoutCommentCreateManyWorkoutInputEnvelope
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
}

export type WorkoutCommentUncheckedCreateNestedManyWithoutWorkoutInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput> | Prisma.WorkoutCommentCreateWithoutWorkoutInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput | Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput[]
  createMany?: Prisma.WorkoutCommentCreateManyWorkoutInputEnvelope
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
}

export type WorkoutCommentUpdateManyWithoutWorkoutNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput> | Prisma.WorkoutCommentCreateWithoutWorkoutInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput | Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput[]
  upsert?: Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutWorkoutInput | Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutWorkoutInput[]
  createMany?: Prisma.WorkoutCommentCreateManyWorkoutInputEnvelope
  set?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  delete?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  update?: Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutWorkoutInput | Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutWorkoutInput[]
  updateMany?: Prisma.WorkoutCommentUpdateManyWithWhereWithoutWorkoutInput | Prisma.WorkoutCommentUpdateManyWithWhereWithoutWorkoutInput[]
  deleteMany?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
}

export type WorkoutCommentUncheckedUpdateManyWithoutWorkoutNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput> | Prisma.WorkoutCommentCreateWithoutWorkoutInput[] | Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput[]
  connectOrCreate?: Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput | Prisma.WorkoutCommentCreateOrConnectWithoutWorkoutInput[]
  upsert?: Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutWorkoutInput | Prisma.WorkoutCommentUpsertWithWhereUniqueWithoutWorkoutInput[]
  createMany?: Prisma.WorkoutCommentCreateManyWorkoutInputEnvelope
  set?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  delete?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  connect?: Prisma.WorkoutCommentWhereUniqueInput | Prisma.WorkoutCommentWhereUniqueInput[]
  update?: Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutWorkoutInput | Prisma.WorkoutCommentUpdateWithWhereUniqueWithoutWorkoutInput[]
  updateMany?: Prisma.WorkoutCommentUpdateManyWithWhereWithoutWorkoutInput | Prisma.WorkoutCommentUpdateManyWithWhereWithoutWorkoutInput[]
  deleteMany?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
}

export type WorkoutCommentCreateWithoutAuthorInput = {
  id?: string
  content: string
  createdAt?: Date | string
  workout: Prisma.WorkoutCreateNestedOneWithoutCommentsInput
}

export type WorkoutCommentUncheckedCreateWithoutAuthorInput = {
  id?: string
  workoutId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentCreateOrConnectWithoutAuthorInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput>
}

export type WorkoutCommentCreateManyAuthorInputEnvelope = {
  data: Prisma.WorkoutCommentCreateManyAuthorInput | Prisma.WorkoutCommentCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type WorkoutCommentUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkoutCommentUpdateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedCreateWithoutAuthorInput>
}

export type WorkoutCommentUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateWithoutAuthorInput, Prisma.WorkoutCommentUncheckedUpdateWithoutAuthorInput>
}

export type WorkoutCommentUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.WorkoutCommentScalarWhereInput
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateManyMutationInput, Prisma.WorkoutCommentUncheckedUpdateManyWithoutAuthorInput>
}

export type WorkoutCommentScalarWhereInput = {
  AND?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
  OR?: Prisma.WorkoutCommentScalarWhereInput[]
  NOT?: Prisma.WorkoutCommentScalarWhereInput | Prisma.WorkoutCommentScalarWhereInput[]
  id?: Prisma.UuidFilter<"WorkoutComment"> | string
  authorId?: Prisma.UuidFilter<"WorkoutComment"> | string
  workoutId?: Prisma.UuidFilter<"WorkoutComment"> | string
  content?: Prisma.StringFilter<"WorkoutComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutComment"> | Date | string
}

export type WorkoutCommentCreateWithoutWorkoutInput = {
  id?: string
  content: string
  createdAt?: Date | string
  author: Prisma.ProfileCreateNestedOneWithoutWorkoutCommentInput
}

export type WorkoutCommentUncheckedCreateWithoutWorkoutInput = {
  id?: string
  authorId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentCreateOrConnectWithoutWorkoutInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput>
}

export type WorkoutCommentCreateManyWorkoutInputEnvelope = {
  data: Prisma.WorkoutCommentCreateManyWorkoutInput | Prisma.WorkoutCommentCreateManyWorkoutInput[]
  skipDuplicates?: boolean
}

export type WorkoutCommentUpsertWithWhereUniqueWithoutWorkoutInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkoutCommentUpdateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedUpdateWithoutWorkoutInput>
  create: Prisma.XOR<Prisma.WorkoutCommentCreateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedCreateWithoutWorkoutInput>
}

export type WorkoutCommentUpdateWithWhereUniqueWithoutWorkoutInput = {
  where: Prisma.WorkoutCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateWithoutWorkoutInput, Prisma.WorkoutCommentUncheckedUpdateWithoutWorkoutInput>
}

export type WorkoutCommentUpdateManyWithWhereWithoutWorkoutInput = {
  where: Prisma.WorkoutCommentScalarWhereInput
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateManyMutationInput, Prisma.WorkoutCommentUncheckedUpdateManyWithoutWorkoutInput>
}

export type WorkoutCommentCreateManyAuthorInput = {
  id?: string
  workoutId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workout?: Prisma.WorkoutUpdateOneRequiredWithoutCommentsNestedInput
}

export type WorkoutCommentUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workoutId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workoutId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentCreateManyWorkoutInput = {
  id?: string
  authorId: string
  content: string
  createdAt?: Date | string
}

export type WorkoutCommentUpdateWithoutWorkoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.ProfileUpdateOneRequiredWithoutWorkoutCommentNestedInput
}

export type WorkoutCommentUncheckedUpdateWithoutWorkoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutCommentUncheckedUpdateManyWithoutWorkoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkoutCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  workoutId?: boolean
  content?: boolean
  createdAt?: boolean
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutComment"]>

export type WorkoutCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  workoutId?: boolean
  content?: boolean
  createdAt?: boolean
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutComment"]>

export type WorkoutCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  workoutId?: boolean
  content?: boolean
  createdAt?: boolean
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutComment"]>

export type WorkoutCommentSelectScalar = {
  id?: boolean
  authorId?: boolean
  workoutId?: boolean
  content?: boolean
  createdAt?: boolean
}

export type WorkoutCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "authorId" | "workoutId" | "content" | "createdAt", ExtArgs["result"]["workoutComment"]>
export type WorkoutCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}
export type WorkoutCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}
export type WorkoutCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
  workout?: boolean | Prisma.WorkoutDefaultArgs<ExtArgs>
}

export type $WorkoutCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkoutComment"
  objects: {
    author: Prisma.$ProfilePayload<ExtArgs>
    workout: Prisma.$WorkoutPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    authorId: string
    workoutId: string
    content: string
    createdAt: Date
  }, ExtArgs["result"]["workoutComment"]>
  composites: {}
}

export type WorkoutCommentGetPayload<S extends boolean | null | undefined | WorkoutCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload, S>

export type WorkoutCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkoutCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkoutCommentCountAggregateInputType | true
  }

export interface WorkoutCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkoutComment'], meta: { name: 'WorkoutComment' } }
  /**
   * Find zero or one WorkoutComment that matches the filter.
   * @param {WorkoutCommentFindUniqueArgs} args - Arguments to find a WorkoutComment
   * @example
   * // Get one WorkoutComment
   * const workoutComment = await prisma.workoutComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkoutCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkoutCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkoutComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkoutCommentFindUniqueOrThrowArgs} args - Arguments to find a WorkoutComment
   * @example
   * // Get one WorkoutComment
   * const workoutComment = await prisma.workoutComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkoutCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkoutCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkoutComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentFindFirstArgs} args - Arguments to find a WorkoutComment
   * @example
   * // Get one WorkoutComment
   * const workoutComment = await prisma.workoutComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkoutCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkoutComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentFindFirstOrThrowArgs} args - Arguments to find a WorkoutComment
   * @example
   * // Get one WorkoutComment
   * const workoutComment = await prisma.workoutComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkoutCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkoutComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkoutComments
   * const workoutComments = await prisma.workoutComment.findMany()
   * 
   * // Get first 10 WorkoutComments
   * const workoutComments = await prisma.workoutComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workoutCommentWithIdOnly = await prisma.workoutComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkoutCommentFindManyArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkoutComment.
   * @param {WorkoutCommentCreateArgs} args - Arguments to create a WorkoutComment.
   * @example
   * // Create one WorkoutComment
   * const WorkoutComment = await prisma.workoutComment.create({
   *   data: {
   *     // ... data to create a WorkoutComment
   *   }
   * })
   * 
   */
  create<T extends WorkoutCommentCreateArgs>(args: Prisma.SelectSubset<T, WorkoutCommentCreateArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkoutComments.
   * @param {WorkoutCommentCreateManyArgs} args - Arguments to create many WorkoutComments.
   * @example
   * // Create many WorkoutComments
   * const workoutComment = await prisma.workoutComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkoutCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkoutComments and returns the data saved in the database.
   * @param {WorkoutCommentCreateManyAndReturnArgs} args - Arguments to create many WorkoutComments.
   * @example
   * // Create many WorkoutComments
   * const workoutComment = await prisma.workoutComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkoutComments and only return the `id`
   * const workoutCommentWithIdOnly = await prisma.workoutComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkoutCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkoutComment.
   * @param {WorkoutCommentDeleteArgs} args - Arguments to delete one WorkoutComment.
   * @example
   * // Delete one WorkoutComment
   * const WorkoutComment = await prisma.workoutComment.delete({
   *   where: {
   *     // ... filter to delete one WorkoutComment
   *   }
   * })
   * 
   */
  delete<T extends WorkoutCommentDeleteArgs>(args: Prisma.SelectSubset<T, WorkoutCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkoutComment.
   * @param {WorkoutCommentUpdateArgs} args - Arguments to update one WorkoutComment.
   * @example
   * // Update one WorkoutComment
   * const workoutComment = await prisma.workoutComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkoutCommentUpdateArgs>(args: Prisma.SelectSubset<T, WorkoutCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkoutComments.
   * @param {WorkoutCommentDeleteManyArgs} args - Arguments to filter WorkoutComments to delete.
   * @example
   * // Delete a few WorkoutComments
   * const { count } = await prisma.workoutComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkoutCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkoutCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkoutComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkoutComments
   * const workoutComment = await prisma.workoutComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkoutCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkoutCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkoutComments and returns the data updated in the database.
   * @param {WorkoutCommentUpdateManyAndReturnArgs} args - Arguments to update many WorkoutComments.
   * @example
   * // Update many WorkoutComments
   * const workoutComment = await prisma.workoutComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkoutComments and only return the `id`
   * const workoutCommentWithIdOnly = await prisma.workoutComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkoutCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkoutCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkoutComment.
   * @param {WorkoutCommentUpsertArgs} args - Arguments to update or create a WorkoutComment.
   * @example
   * // Update or create a WorkoutComment
   * const workoutComment = await prisma.workoutComment.upsert({
   *   create: {
   *     // ... data to create a WorkoutComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkoutComment we want to update
   *   }
   * })
   */
  upsert<T extends WorkoutCommentUpsertArgs>(args: Prisma.SelectSubset<T, WorkoutCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkoutCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkoutCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkoutComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentCountArgs} args - Arguments to filter WorkoutComments to count.
   * @example
   * // Count the number of WorkoutComments
   * const count = await prisma.workoutComment.count({
   *   where: {
   *     // ... the filter for the WorkoutComments we want to count
   *   }
   * })
  **/
  count<T extends WorkoutCommentCountArgs>(
    args?: Prisma.Subset<T, WorkoutCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkoutCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkoutComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkoutCommentAggregateArgs>(args: Prisma.Subset<T, WorkoutCommentAggregateArgs>): Prisma.PrismaPromise<GetWorkoutCommentAggregateType<T>>

  /**
   * Group by WorkoutComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkoutCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkoutCommentGroupByArgs['orderBy'] }
      : { orderBy?: WorkoutCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkoutCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkoutCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkoutComment model
 */
readonly fields: WorkoutCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkoutComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkoutCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  author<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  workout<T extends Prisma.WorkoutDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkoutDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkoutClient<runtime.Types.Result.GetResult<Prisma.$WorkoutPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkoutComment model
 */
export interface WorkoutCommentFieldRefs {
  readonly id: Prisma.FieldRef<"WorkoutComment", 'String'>
  readonly authorId: Prisma.FieldRef<"WorkoutComment", 'String'>
  readonly workoutId: Prisma.FieldRef<"WorkoutComment", 'String'>
  readonly content: Prisma.FieldRef<"WorkoutComment", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorkoutComment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkoutComment findUnique
 */
export type WorkoutCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutComment to fetch.
   */
  where: Prisma.WorkoutCommentWhereUniqueInput
}

/**
 * WorkoutComment findUniqueOrThrow
 */
export type WorkoutCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutComment to fetch.
   */
  where: Prisma.WorkoutCommentWhereUniqueInput
}

/**
 * WorkoutComment findFirst
 */
export type WorkoutCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutComment to fetch.
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutComments to fetch.
   */
  orderBy?: Prisma.WorkoutCommentOrderByWithRelationInput | Prisma.WorkoutCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkoutComments.
   */
  cursor?: Prisma.WorkoutCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkoutComments.
   */
  distinct?: Prisma.WorkoutCommentScalarFieldEnum | Prisma.WorkoutCommentScalarFieldEnum[]
}

/**
 * WorkoutComment findFirstOrThrow
 */
export type WorkoutCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutComment to fetch.
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutComments to fetch.
   */
  orderBy?: Prisma.WorkoutCommentOrderByWithRelationInput | Prisma.WorkoutCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkoutComments.
   */
  cursor?: Prisma.WorkoutCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkoutComments.
   */
  distinct?: Prisma.WorkoutCommentScalarFieldEnum | Prisma.WorkoutCommentScalarFieldEnum[]
}

/**
 * WorkoutComment findMany
 */
export type WorkoutCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutComments to fetch.
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutComments to fetch.
   */
  orderBy?: Prisma.WorkoutCommentOrderByWithRelationInput | Prisma.WorkoutCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkoutComments.
   */
  cursor?: Prisma.WorkoutCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutComments.
   */
  skip?: number
  distinct?: Prisma.WorkoutCommentScalarFieldEnum | Prisma.WorkoutCommentScalarFieldEnum[]
}

/**
 * WorkoutComment create
 */
export type WorkoutCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkoutComment.
   */
  data: Prisma.XOR<Prisma.WorkoutCommentCreateInput, Prisma.WorkoutCommentUncheckedCreateInput>
}

/**
 * WorkoutComment createMany
 */
export type WorkoutCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkoutComments.
   */
  data: Prisma.WorkoutCommentCreateManyInput | Prisma.WorkoutCommentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkoutComment createManyAndReturn
 */
export type WorkoutCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * The data used to create many WorkoutComments.
   */
  data: Prisma.WorkoutCommentCreateManyInput | Prisma.WorkoutCommentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkoutComment update
 */
export type WorkoutCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkoutComment.
   */
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateInput, Prisma.WorkoutCommentUncheckedUpdateInput>
  /**
   * Choose, which WorkoutComment to update.
   */
  where: Prisma.WorkoutCommentWhereUniqueInput
}

/**
 * WorkoutComment updateMany
 */
export type WorkoutCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkoutComments.
   */
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateManyMutationInput, Prisma.WorkoutCommentUncheckedUpdateManyInput>
  /**
   * Filter which WorkoutComments to update
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * Limit how many WorkoutComments to update.
   */
  limit?: number
}

/**
 * WorkoutComment updateManyAndReturn
 */
export type WorkoutCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * The data used to update WorkoutComments.
   */
  data: Prisma.XOR<Prisma.WorkoutCommentUpdateManyMutationInput, Prisma.WorkoutCommentUncheckedUpdateManyInput>
  /**
   * Filter which WorkoutComments to update
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * Limit how many WorkoutComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkoutComment upsert
 */
export type WorkoutCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkoutComment to update in case it exists.
   */
  where: Prisma.WorkoutCommentWhereUniqueInput
  /**
   * In case the WorkoutComment found by the `where` argument doesn't exist, create a new WorkoutComment with this data.
   */
  create: Prisma.XOR<Prisma.WorkoutCommentCreateInput, Prisma.WorkoutCommentUncheckedCreateInput>
  /**
   * In case the WorkoutComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkoutCommentUpdateInput, Prisma.WorkoutCommentUncheckedUpdateInput>
}

/**
 * WorkoutComment delete
 */
export type WorkoutCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
  /**
   * Filter which WorkoutComment to delete.
   */
  where: Prisma.WorkoutCommentWhereUniqueInput
}

/**
 * WorkoutComment deleteMany
 */
export type WorkoutCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkoutComments to delete
   */
  where?: Prisma.WorkoutCommentWhereInput
  /**
   * Limit how many WorkoutComments to delete.
   */
  limit?: number
}

/**
 * WorkoutComment without action
 */
export type WorkoutCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutComment
   */
  select?: Prisma.WorkoutCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutComment
   */
  omit?: Prisma.WorkoutCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutCommentInclude<ExtArgs> | null
}
