
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const TeamRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type TeamRole = (typeof TeamRole)[keyof typeof TeamRole]


export const ChallengeParticipantType = {
  INDIVIDUAL: 'INDIVIDUAL',
  TEAM: 'TEAM'
} as const

export type ChallengeParticipantType = (typeof ChallengeParticipantType)[keyof typeof ChallengeParticipantType]
